# Библиотека Implicit

## 1. Описание библиотеки

**Implicit** — это библиотека Python, предназначенная для работы с неявными (implicit) предпочтениями пользователей в рекомендательных системах. Разработанная Бенджамином Картером (Benjamin Carter) и поддерживаемая активным сообществом, библиотека фокусируется на инструментах для работы с методами факторизационных машин (factorization machines) и другими алгоритмами, используемыми для обработки неявных предпочтений.

Основное назначение библиотеки Implicit заключается в создании рекомендательных систем, основанных на факторизации матриц. Она особенно полезна для задач коллаборативной фильтрации, таких как рекомендации товаров пользователям на основе их предыдущих взаимодействий с этими товарами.

### Основные особенности библиотеки Implicit:

1. **Работа с неявными предпочтениями:**
   - В отличие от явных предпочтений (explicit preferences), когда пользователи прямо выражают свою оценку объектов (например, ставя звездочки фильмам), неявные предпочтения подразумеваются косвенно через поведение пользователя (например, клики, просмотры страниц, добавление в корзину). Implicit специализируется именно на обработке таких данных.

2. **Реализация алгоритмов факторизационных машин - Factorization Machines (FM):**
    - **Alternating Least Squares (ALS)**: Алгоритм чередующихся наименьших квадратов, который хорошо подходит для задач с плотными матрицами взаимодействия пользователей и предметов.
    - **Bayesian Personalized Ranking (BPR)**: Байесовский персонализированный ранжирующий алгоритм, ориентированный на максимизацию вероятности того, что пользователь выберет один объект перед другим.
    - **Logistic Matrix Factorization (LMF)**: Логистическая факторизация матриц, которая использует логистическую функцию для минимизации ошибки прогнозирования.

3. **Реализация алгоритмов коллаборативной фильтрации item-based (Алгоритмы k-ближайших соседей (KNN)):**
   - **CosineRecommender**: реализует алгоритм ближайших соседей на основе косинусного расстояния между элементами. Косинусное расстояние измеряет угол между двумя векторами, представляющими элементы, и является популярным методом для определения подобия в векторных пространствах. Эта модель подходит для случаев, когда необходимо учитывать направление векторов, а не их длину.
    - **TFIDFRecommender**: строит рекомендации на основе TF-IDF (Term Frequency-Inverse Document Frequency) расстояний между элементами. TF-IDF взвешивает термины таким образом, что редкие термины получают больший вес, чем частые. Этот метод полезен, когда нужно учесть важность редких событий или взаимодействий.
    - **BM25Recommender**: использует метрику BM25 (Best Match 25) для расчета подобия между элементами. BM25 является улучшенной версией TF-IDF, которая учитывает длину документа и частоту термина в документе. Этот метод эффективен для поиска релевантных документов в больших коллекциях текстов.

4. **Оптимизированная производительность:**
   - Для ускорения вычислений критически важные части кода написаны на Cython, что существенно повышает производительность библиотеки при работе с большими объемами данных.
   - Поддерживается многопоточное выполнение операций, что позволяет эффективно использовать ресурсы многоядерных процессоров.

5. **Удобство использования:**
   - Implicit предоставляет простой и интуитивно понятный API, который облегчает подготовку данных, обучение моделей и получение рекомендаций. Это делает библиотеку удобной для интеграции в существующие проекты.

6. **Открытый исходный код:**
   - Исходный код библиотеки доступен на GitHub, что дает возможность пользователям вносить изменения и улучшения, а также участвовать в развитии проекта. Открытая экосистема способствует активному обсуждению и улучшению функционала библиотеки.

### Преимущества использования Implicit:

- **Эффективность:** библиотека оптимизирована для работы с большими массивами данных, что делает ее подходящей для крупных проектов.
- **Широкий спектр алгоритмов:** наличие нескольких алгоритмов позволяет выбрать наиболее подходящий для конкретных задач и данных.
- **Совместимость:** Implicit легко интегрируется с популярными фреймворками для машинного обучения, такими как Scikit-learn и TensorFlow.
- **Активное сообщество:** постоянная поддержка и развитие библиотеки благодаря активному сообществу разработчиков и пользователей.


**Установка**
1. Для установки Implicit вам потребуется Python версии 3.6 или выше. Вы можете установить библиотеку через pip:
```
pip install implicit
```
2. Установить Implicit можно с помощью conda:
```
# CPU only package
conda install -c conda-forge implicit
# CPU+GPU package
conda install -c conda-forge implicit implicit-proc=*=gpu
```

**Документация и ресурсы**
* [Официальный сайт](https://implicit.io/)
* [Страница на PyPi](https://pypi.org/project/implicit/)
* [Репозиторий на GitHub](https://github.com/benfred/implicit)

In [1]:
# загружаем необходимые библиотеки, методы и функции
import numpy as np  # импортируем NumPy для работы с массивами и матрицами
import pandas as pd  # импортируем Pandas для работы с таблицами данных
import time # импортируем функцию для работы со временем выполнения кода

from implicit.datasets.lastfm import get_lastfm # функцию для загрузки данных
from implicit.nearest_neighbours import bm25_weight  # импортируем функцию для вычисления веса BM25
from implicit.als import AlternatingLeastSquares  # импортируем алгоритм ALS
from implicit.cpu.bpr import BayesianPersonalizedRanking  # импортируем алгоритм BPR
from implicit.cpu.lmf import LogisticMatrixFactorization  # импортируем алгоритм LMF
from implicit.nearest_neighbours import CosineRecommender  # импортируем алгоритм CosineRecommender
from implicit.nearest_neighbours import TFIDFRecommender  # импортируем алгоритм TFIDFRecommender
from implicit.nearest_neighbours import ItemItemRecommender  # импортируем базовый класс для алгоритмов Item-Item
from implicit.nearest_neighbours import BM25Recommender  # импортируем алгоритм BM25Recommender
from implicit.ann.nmslib import NMSLibModel # импортируем алгоритм NMSLib
from implicit.evaluation import train_test_split  # импортируем функцию для разделения данных на обучающую и тестовую выборки
from implicit.evaluation import precision_at_k  # импортируем функцию для вычисления точности на уровне k

from scipy.sparse import csr_matrix  # импортируем функцию для работы с разреженными матрицами

import optuna # библиотека подбора гиперпараметров ML моделей

from joblib import dump, load # библиотека для сохранения и загрузки моделей

# фиксируем RANDOM_SEED, для воспроизводимости кода.
RANDOM_SEED = 369

# отключаем предупреждения
import warnings 
warnings.filterwarnings("ignore")

# увеличиваем количество отображаемых столбцов и строк
pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", 3000)

%load_ext watermark
%watermark -n -u -v -iv -w

Last updated: Fri Jan 17 2025

Python implementation: CPython
Python version       : 3.11.11
IPython version      : 8.31.0

scipy   : 1.13.1
numpy   : 1.23.5
joblib  : 1.4.2
pandas  : 2.2.3
implicit: 0.7.2
optuna  : 4.1.0

Watermark: 2.5.0

**Установка необходимых библиотеки**

In [2]:
# conda install -c conda-forge optuna
# conda install -c conda-forge implicit

* [GitHub_Watermark](https://github.com/rasbt/watermark?tab=readme-ov-file#installation-and-updating)

In [3]:
# pip install watermark
# pip install --upgrade jupyter ipywidgets
# pip install --upgrade pip setuptools
# pip install recommenders

**Фиксируем версии установленных пакетов**

In [4]:
# conda env export > environment_fp_implicit.yml

In [2]:
# cоздаем пустой DataFrame для хранения результатов
results_implicit = pd.DataFrame(columns=["Model", "Time", "train_Precision@3", "test_Precision@3"])

# функция для добавления результатов в results_lightfm
def add_results(results_implicit, model_name, elapsed_time, train_precision, test_precision):
    """_summary_

    Args:
        results_lightfm (_type_): _description_
        model_name (_type_): _description_
        elapsed_time (_type_): _description_
        train_precision (_type_): _description_
        test_precision (_type_): _description_

    Returns:
        _type_: _description_
    """
    new_row = pd.Series({
        "Model": model_name,
        "Time": elapsed_time,
        "train_Precision@3": train_precision,
        "test_Precision@3": test_precision
    })
    results_implicit = pd.concat([results_implicit, new_row.to_frame().T], ignore_index=True)
    return results_implicit  # возвращаем обновленный датафрейм

In [3]:
# загружаем данные
df = pd.read_csv("data/data_light_count.csv", sep=",")
# нормализуем visitorid и itemid
min_visitorid = df['visitorid'].min()
max_visitorid = df['visitorid'].max()
min_itemid = df['itemid'].min()
max_itemid = df['itemid'].max()

normalized_df = df.copy()
normalized_df['visitorid'] -= min_visitorid
normalized_df['itemid'] -= min_itemid

# уникальные пользователи и элементы
users = sorted(normalized_df['visitorid'].unique())
items = sorted(normalized_df['itemid'].unique())

# создаем словарь для маппинга id на индексы
user_to_idx = {u: i for i, u in enumerate(users)}
item_to_idx = {i: j for j, i in enumerate(items)}

# преобразуем значения в индексы
row = normalized_df['visitorid'].map(user_to_idx)
col = normalized_df['itemid'].map(item_to_idx)
values = normalized_df['like']

# создаем разреженную матрицу
matrix = csr_matrix((values, (row, col)), shape=(len(users), len(items)))

# взвешивание матрицы с помощью BM25
matrix = bm25_weight(matrix, K1=40, B=1.7)
# преобразование обратно в CSR-матрицу
matrix = matrix.tocsr()

# формируем тренировочную и тестовую выборки
train, test = train_test_split(matrix, train_percentage=0.8, random_state=RANDOM_SEED)

In [4]:
# Оценим размеры обучающей и тестовой выборки
print(f'Размер обучающей выборки: {train.shape}')
print(f'Размер тестовой выборки: {test.shape}')

Размер обучающей выборки: (58627, 95302)
Размер тестовой выборки: (58627, 95302)

## 2. Построение моделей на базе алгоритмов "Коллаборативной фильтрация (англ. Collaborative Filtering)"

**Коллаборативная фильтрация (англ. Collaborative Filtering)** — это одна из ключевых техник, применяемых в рекомендательных системах для предсказания предпочтений пользователей на основе их прошлых взаимодействий с объектами (например, покупки товаров, просмотр фильмов, прослушивание музыки и т.д.). Основная идея заключается в том, что пользователи с похожими вкусами или поведением склонны выбирать одинаковые объекты. Таким образом, система может рекомендовать новые объекты одному пользователю на основании того, что эти объекты понравились другим пользователям с аналогичными предпочтениями.

### Принципы работы коллаборативной фильтрации:

1. **Сбор данных о взаимодействии пользователей и объектов:**
   - Система собирает информацию о том, какие объекты (фильмы, книги, товары и т.д.) пользователи оценили, купили, посмотрели или добавили в избранное. Это могут быть как явные оценки (рейтинги), так и неявные признаки интереса (просмотры, клики, добавления в корзину).

2. **Определение схожести между пользователями или объектами:**
   - На основе собранных данных система вычисляет степень схожести между пользователями или объектами. Например, если два пользователя оценили одинаково несколько фильмов, считается, что их вкусы похожи.

3. **Предсказание предпочтений:**
   - Когда системе нужно сделать рекомендацию новому пользователю, она ищет пользователей с похожими предпочтениями и предлагает ему объекты, которые понравились этим пользователям, но ещё не были оценены новым пользователем.

### Типы коллаборативной фильтрации:

1. **User-based (основанный на пользователях):**
   - Этот подход ищет пользователей с похожими вкусами и рекомендует объекты, которые понравились этим пользователям. Пример: если Анна и Борис любят одни и те же фильмы, системе стоит порекомендовать Анне фильмы, которые Борис смотрел, но Анна ещё нет.

2. **Item-based (основанный на объектах):**
   - Этот подход ищет объекты, подобные тем, которые пользователь уже оценил положительно, и рекомендует их. Пример: если Анна любит фильмы жанра комедии, системе следует предложить ей другие комедии, которые она ещё не смотрела.

### Преимущества коллаборативной фильтрации:

- **Универсальность:** Может применяться в различных сферах, таких как электронная коммерция, музыкальные сервисы, видеостриминг и социальные сети.
- **Простота внедрения:** Не требует глубокого понимания предметной области, достаточно иметь данные о взаимодействиях пользователей и объектов.
- **Высокое качество рекомендаций:** Часто даёт точные и релевантные рекомендации, особенно в условиях большого количества данных.

### Недостатки коллаборативной фильтрации:

- **Холодный старт:** Трудно делать рекомендации новым пользователям или объектам, пока не накоплено достаточное количество данных о них.
- **Проблема спама:** Могут возникнуть сложности с фильтрацией ложных рейтингов или отзывов, что может исказить результаты.
- **Разреженность данных:** Матрица взаимодействий пользователей и объектов часто бывает очень разреженной, что усложняет обработку данных.

### Примеры использования:

- **Amazon:** Рекомендует товары на основе покупок и просмотров других пользователей.
- **Netflix:** Предлагает фильмы и сериалы на основе того, что смотрели и оценивали другие зрители.
- **Spotify:** Подбирает плейлисты и треки на основе музыкальных предпочтений пользователей.

Коллаборативная фильтрация остаётся одной из самых популярных и эффективных технологий для создания персональных рекомендаций, несмотря на свои недостатки.

### 2.1. Модель "NNM CosineRecomender"

**Модель `CosineRecommender`** из библиотеки Implicit использует косинусное сходство для расчета рекомендаций. Косинусное сходство измеряет угол между двумя векторами, что позволяет оценить схожесть между пользователями или элементами на основе их предпочтений. Рассмотрим ключевые параметры этой модели и предложим разумные диапазоны значений для них.

#### Основные параметры модели CosineRecommender:

1. **K**: Количество ближайших соседей, которые используются для формирования рекомендаций. Этот параметр влияет на точность и разнообразие рекомендаций. Чем больше значение K, тем больше элементов будет рассматриваться для формирования рекомендаций, однако это может увеличить вычислительные затраты. **Рекомендуемые значения:** 5–50.

2. **num_threads**: Количество потоков, используемых для параллельных вычислений. Этот параметр важен для увеличения скорости обработки больших наборов данных.

In [5]:
# фиксируем время начала работы
start_time = time.time()
# формируем параметры модели и обучаем её
model = CosineRecommender(
    K=16,             # стандартное количество ближайших соседей
    num_threads=8     # количество ядер
)

model.fit(train)

# расчитываем метрику precision@k
p_at_k = precision_at_k(model, train, test, K=3)
p_at_k_train = 0
# фиксируем время окончания работы
end_time = time.time()
elapsed_time = end_time - start_time

print(f'Precision@3: {p_at_k:.4f}')
print()

# Вариан 1 - Выбираем случайного пользователя
random_normalized_visitorid = np.random.choice(users)

# Вариант 2 - Вводим оригинальный visitorid
# original_visitorid = 391657
# random_normalized_visitorid = original_visitorid - min_visitorid # приводим его к нормализованному виду

userid = user_to_idx[random_normalized_visitorid]

# получаем рекомендации для пользователя
ids, scores = model.recommend(userid, matrix[userid], N=3, filter_already_liked_items=False)
# преобразуем обратно в оригинальные itemid
original_item_ids = [items[idx] + min_itemid for idx in ids]
# преобразуем обратно в оригинальный visitorid
original_visitorid = random_normalized_visitorid + min_visitorid

# используем pandas для отображения результатов в виде таблицы
rec_user = pd.DataFrame({
    "visitorid": original_visitorid,
    "itemid": original_item_ids,
    "score": scores,
    "already_liked": np.in1d(ids, matrix[userid].indices.ravel())  # преобразуем в одномерный массив
})
print(rec_user)
print()
set1 = set(df[df["visitorid"] == original_visitorid]["itemid"].unique().tolist())
set2 = set(original_item_ids)
print(f'Соответсвие itemid между рекомендациями и фактом {set1&set2}')
print()
print(rec_user["already_liked"].value_counts())

# сохраняем результаты
results_implicit = add_results(results_implicit, "NNM_CosinRecomender", elapsed_time, p_at_k_train, p_at_k)
display(results_implicit)

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

Precision@3: 0.0512

   visitorid  itemid       score  already_liked
0      85590  192193  296.707462           True
1      85590   74174  195.708965          False
2      85590    3462  133.688184          False

Соответсвие itemid между рекомендациями и фактом {192193}

already_liked
False    2
True     1
Name: count, dtype: int64

                 Model      Time train_Precision@3 test_Precision@3
0  NNM_CosinRecomender  4.854386                 0         0.051156

### Подбор гиперпараметров с помощью **OPTUNA**

In [6]:
%%time
def objective(trial):
    # Получаем гиперпараметры из trial
    K = trial.suggest_int('K', 1, 50)
    
    # Обучаем модель с новыми параметрами
    model = CosineRecommender(
        K=K,
        num_threads=8
    )
    
    model.fit(train)

    # Оцениваем модель
    p_at_k = precision_at_k(model, train, test, K=3)
    
    return p_at_k

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20, show_progress_bar=True)

best_params = study.best_trial.params
print("Лучшие параметры:", best_params)

[I 2025-01-17 13:44:39,941] A new study created in memory with name: no-name-fb8541f5-dfc9-4273-9ba6-9d3c3f8df37d

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:44:44,964] Trial 0 finished with value: 0.05238653044883676 and parameters: {'K': 48}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:44:49,501] Trial 1 finished with value: 0.051734108331726994 and parameters: {'K': 24}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:44:53,943] Trial 2 finished with value: 0.04838303109384499 and parameters: {'K': 9}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:44:58,712] Trial 3 finished with value: 0.0523717026734479 and parameters: {'K': 49}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:45:03,631] Trial 4 finished with value: 0.05122996396850581 and parameters: {'K': 19}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:45:08,064] Trial 5 finished with value: 0.051244791743894666 and parameters: {'K': 18}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:45:12,821] Trial 6 finished with value: 0.05206031939028188 and parameters: {'K': 29}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:45:17,192] Trial 7 finished with value: 0.03663943298586913 and parameters: {'K': 3}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:45:21,748] Trial 8 finished with value: 0.051244791743894666 and parameters: {'K': 18}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:45:26,352] Trial 9 finished with value: 0.05137824172239439 and parameters: {'K': 20}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:45:31,432] Trial 10 finished with value: 0.05238653044883676 and parameters: {'K': 50}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:45:36,213] Trial 11 finished with value: 0.05238653044883676 and parameters: {'K': 50}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:45:40,881] Trial 12 finished with value: 0.05231239157189247 and parameters: {'K': 41}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:45:45,765] Trial 13 finished with value: 0.05235687489805904 and parameters: {'K': 38}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:45:50,590] Trial 14 finished with value: 0.0523717026734479 and parameters: {'K': 39}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:45:55,655] Trial 15 finished with value: 0.05234204712267019 and parameters: {'K': 45}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:46:00,348] Trial 16 finished with value: 0.0521937693687816 and parameters: {'K': 33}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:46:05,375] Trial 17 finished with value: 0.05234204712267019 and parameters: {'K': 44}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:46:10,105] Trial 18 finished with value: 0.052238252694948174 and parameters: {'K': 34}. Best is trial 0 with value: 0.05238653044883676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:46:15,084] Trial 19 finished with value: 0.05235687489805904 and parameters: {'K': 46}. Best is trial 0 with value: 0.05238653044883676.
Лучшие параметры: {'K': 48}
CPU times: user 2min 14s, sys: 23.5 s, total: 2min 37s
Wall time: 1min 35s

In [7]:
# визуализация среза
optuna.visualization.plot_slice(study, target_name="p_at_k")

In [8]:
# фиксируем время начала работы
start_time = time.time()
# формируем параметры модели и обучаем её с учетом подобранных параметров
model = CosineRecommender(**best_params, 
                          num_threads=8)

model.fit(train)

# расчитываем метрику precision@k
p_at_k = precision_at_k(model, train, test, K=3)
p_at_k_train = 0
# фиксируем время окончания работы
end_time = time.time()
elapsed_time = end_time - start_time

print(f'Precision@3: {p_at_k:.4f}', f'Параметры модели: {best_params}')
print()
# Вариан 1 - Выбираем случайного пользователя
random_normalized_visitorid = np.random.choice(users)

# Вариант 2 - Вводим оригинальный visitorid
# original_visitorid = 391657
# random_normalized_visitorid = original_visitorid - min_visitorid # приводим его к нормализованному виду

userid = user_to_idx[random_normalized_visitorid]

# получаем рекомендации для пользователя
ids, scores = model.recommend(userid, matrix[userid], N=3, filter_already_liked_items=False)
# преобразуем обратно в оригинальные itemid
original_item_ids = [items[idx] + min_itemid for idx in ids]
# преобразуем обратно в оригинальный visitorid
original_visitorid = random_normalized_visitorid + min_visitorid

# используем pandas для отображения результатов в виде таблицы
rec_user = pd.DataFrame({
    "visitorid": original_visitorid,
    "itemid": original_item_ids,
    "score": scores,
    "already_liked": np.in1d(ids, matrix[userid].indices.ravel())  # преобразуем в одномерный массив
})
print(rec_user)
print()
set1 = set(df[df["visitorid"] == original_visitorid]["itemid"].unique().tolist())
set2 = set(original_item_ids)
print(f'Соответсвие itemid между рекомендациями и фактом {set1&set2}')
print()
print(rec_user["already_liked"].value_counts())

# сохраняем результаты
results_implicit = add_results(results_implicit, "NNM_CosinRecomender_Optuna", elapsed_time, p_at_k_train, p_at_k)
display(results_implicit)

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

Precision@3: 0.0524 Параметры модели: {'K': 48}

   visitorid  itemid      score  already_liked
0    1399429  198400  42.151121           True
1    1399429  412230  34.609188           True
2    1399429  450685  30.469251          False

Соответсвие itemid между рекомендациями и фактом {198400, 412230}

already_liked
True     2
False    1
Name: count, dtype: int64

                        Model      Time train_Precision@3 test_Precision@3
0         NNM_CosinRecomender  4.854386                 0         0.051156
1  NNM_CosinRecomender_Optuna  5.049159                 0         0.052387

### 2.2. Модель `NNM ItemItemRecommender`

**Модель `ItemItemRecommender`** из библиотеки Implicit реализует коллаборативную фильтрацию на уровне элементов (item-to-item collaborative filtering). Эта модель находит похожие элементы на основе истории взаимодействий пользователей и делает рекомендации на основе этих похожих элементов. Рассмотрим ключевые параметры этой модели и предложим разумные диапазоны значений для них.

#### Основные параметры модели ItemItemRecommender:

1. **K**: Количество ближайших соседей, которые используются для формирования рекомендаций. Этот параметр влияет на точность и разнообразие рекомендаций. Чем больше значение K, тем больше элементов будет рассматриваться для формирования рекомендаций, однако это может увеличить вычислительные затраты. **Рекомендуемые значения:** 5–50

2. **num_threads**: Количество потоков, используемых для параллельных вычислений. Этот параметр важен для увеличения скорости обработки больших наборов данных.

In [9]:
# фиксируем время начала работы
start_time = time.time()
# формируем параметры модели и обучаем её
model = ItemItemRecommender(
    K=15,                 # Увеличим количество ближайших соседей для большей точности
    num_threads=8         # Используем несколько потоков для ускорения
)

model.fit(train)

# расчитываем метрику precision@k
p_at_k = precision_at_k(model, train, test, K=3)
p_at_k_train = 0
# фиксируем время окончания работы
end_time = time.time()
elapsed_time = end_time - start_time

print(f'Precision@3: {p_at_k:.4f}')
print()

# Вариан 1 - Выбираем случайного пользователя
random_normalized_visitorid = np.random.choice(users)

# Вариант 2 - Вводим оригинальный visitorid
# original_visitorid = 391657
# random_normalized_visitorid = original_visitorid - min_visitorid # приводим его к нормализованному виду

userid = user_to_idx[random_normalized_visitorid]

# получаем рекомендации для пользователя
ids, scores = model.recommend(userid, matrix[userid], N=3, filter_already_liked_items=False)
# преобразуем обратно в оригинальные itemid
original_item_ids = [items[idx] + min_itemid for idx in ids]
# преобразуем обратно в оригинальный visitorid
original_visitorid = random_normalized_visitorid + min_visitorid

# используем pandas для отображения результатов в виде таблицы
rec_user = pd.DataFrame({
    "visitorid": original_visitorid,
    "itemid": original_item_ids,
    "score": scores,
    "already_liked": np.in1d(ids, matrix[userid].indices.ravel())  # преобразуем в одномерный массив
})
print(rec_user)
print()
set1 = set(df[df["visitorid"] == original_visitorid]["itemid"].unique().tolist())
set2 = set(original_item_ids)
print(f'Соответсвие itemid между рекомендациями и фактом {set1&set2}')
print()
print(rec_user["already_liked"].value_counts())

# сохраняем результаты
results_implicit = add_results(results_implicit, "NNM_ItemItemRecomender", elapsed_time, p_at_k_train, p_at_k)
display(results_implicit)

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

Precision@3: 0.0713

   visitorid  itemid         score  already_liked
0     264429  146260  5.524348e+07           True
1     264429  323172  4.833717e+07           True
2     264429   55112  1.410566e+07          False

Соответсвие itemid между рекомендациями и фактом {323172, 146260}

already_liked
True     2
False    1
Name: count, dtype: int64

                        Model      Time train_Precision@3 test_Precision@3
0         NNM_CosinRecomender  4.854386                 0         0.051156
1  NNM_CosinRecomender_Optuna  5.049159                 0         0.052387
2      NNM_ItemItemRecomender  4.798687                 0         0.071307

### Подбор гиперпараметров с помощью **OPTUNA**

In [10]:
%%time
def objective(trial):
    # Получаем гиперпараметры из trial
    K = trial.suggest_int('K', 1, 50)
    
    # Обучаем модель с новыми параметрами
    model = ItemItemRecommender(
        K=K,
        num_threads=8
    )
    
    model.fit(train)

    # Оцениваем модель
    p_at_k = precision_at_k(model, train, test, K=3)
    
    return p_at_k

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20, show_progress_bar=True)

best_params = study.best_trial.params
print("Лучшие параметры:", best_params)

[I 2025-01-17 13:46:55,549] A new study created in memory with name: no-name-49858570-653e-4e82-9373-f27aa14a29c3

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:47:00,439] Trial 0 finished with value: 0.0716626384543527 and parameters: {'K': 16}. Best is trial 0 with value: 0.0716626384543527.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:47:05,375] Trial 1 finished with value: 0.07293782713779452 and parameters: {'K': 39}. Best is trial 1 with value: 0.07293782713779452.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:47:09,857] Trial 2 finished with value: 0.07102504411263179 and parameters: {'K': 13}. Best is trial 1 with value: 0.07293782713779452.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:47:14,211] Trial 3 finished with value: 0.0672736169392506 and parameters: {'K': 6}. Best is trial 1 with value: 0.07293782713779452.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:47:19,470] Trial 4 finished with value: 0.07298231046396109 and parameters: {'K': 48}. Best is trial 4 with value: 0.07298231046396109.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:47:24,305] Trial 5 finished with value: 0.07296748268857223 and parameters: {'K': 37}. Best is trial 4 with value: 0.07298231046396109.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:47:28,961] Trial 6 finished with value: 0.07222609391912932 and parameters: {'K': 20}. Best is trial 4 with value: 0.07298231046396109.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:47:33,461] Trial 7 finished with value: 0.06946812769680165 and parameters: {'K': 9}. Best is trial 4 with value: 0.07298231046396109.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:47:38,198] Trial 8 finished with value: 0.07225574946990702 and parameters: {'K': 21}. Best is trial 4 with value: 0.07298231046396109.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:47:42,581] Trial 9 finished with value: 0.07111401076496493 and parameters: {'K': 14}. Best is trial 4 with value: 0.07298231046396109.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:47:47,362] Trial 10 finished with value: 0.07299713823934995 and parameters: {'K': 46}. Best is trial 10 with value: 0.07299713823934995.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:47:52,333] Trial 11 finished with value: 0.07298231046396109 and parameters: {'K': 50}. Best is trial 10 with value: 0.07299713823934995.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:47:57,124] Trial 12 finished with value: 0.07298231046396109 and parameters: {'K': 50}. Best is trial 10 with value: 0.07299713823934995.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:48:02,023] Trial 13 finished with value: 0.07293782713779452 and parameters: {'K': 38}. Best is trial 10 with value: 0.07299713823934995.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:48:06,685] Trial 14 finished with value: 0.07287851603623909 and parameters: {'K': 31}. Best is trial 10 with value: 0.07299713823934995.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:48:11,748] Trial 15 finished with value: 0.07299713823934995 and parameters: {'K': 44}. Best is trial 10 with value: 0.07299713823934995.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:48:16,521] Trial 16 finished with value: 0.07298231046396109 and parameters: {'K': 43}. Best is trial 10 with value: 0.07299713823934995.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:48:21,737] Trial 17 finished with value: 0.07292299936240566 and parameters: {'K': 29}. Best is trial 10 with value: 0.07299713823934995.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:48:26,755] Trial 18 finished with value: 0.07298231046396109 and parameters: {'K': 43}. Best is trial 10 with value: 0.07299713823934995.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:48:31,516] Trial 19 finished with value: 0.0729081715870168 and parameters: {'K': 32}. Best is trial 10 with value: 0.07299713823934995.
Лучшие параметры: {'K': 46}
CPU times: user 2min 17s, sys: 23.8 s, total: 2min 40s
Wall time: 1min 35s

In [11]:
# визуализация среза
optuna.visualization.plot_slice(study, target_name="p_at_k")

In [12]:
# фиксируем время начала работы
start_time = time.time()
# формируем параметры модели и обучаем её с учетом подобранных параметров
model = ItemItemRecommender(**best_params, 
                        num_threads=8)


model.fit(train)

# расчитываем метрику precision@k
p_at_k = precision_at_k(model, train, test, K=3)
p_at_k_train = 0
# фиксируем время окончания работы
end_time = time.time()
elapsed_time = end_time - start_time

print(f'Precision@3: {p_at_k:.4f}', f'Параметры модели: {best_params}')
print()
# Вариан 1 - Выбираем случайного пользователя
random_normalized_visitorid = np.random.choice(users)

# Вариант 2 - Вводим оригинальный visitorid
# original_visitorid = 391657
# random_normalized_visitorid = original_visitorid - min_visitorid # приводим его к нормализованному виду

userid = user_to_idx[random_normalized_visitorid]

# получаем рекомендации для пользователя
ids, scores = model.recommend(userid, matrix[userid], N=3, filter_already_liked_items=False)
# преобразуем обратно в оригинальные itemid
original_item_ids = [items[idx] + min_itemid for idx in ids]
# преобразуем обратно в оригинальный visitorid
original_visitorid = random_normalized_visitorid + min_visitorid

# используем pandas для отображения результатов в виде таблицы
rec_user = pd.DataFrame({
    "visitorid": original_visitorid,
    "itemid": original_item_ids,
    "score": scores,
    "already_liked": np.in1d(ids, matrix[userid].indices.ravel())  # преобразуем в одномерный массив
})
print(rec_user)
print()
set1 = set(df[df["visitorid"] == original_visitorid]["itemid"].unique().tolist())
set2 = set(original_item_ids)
print(f'Соответсвие itemid между рекомендациями и фактом {set1&set2}')
print()
print(rec_user["already_liked"].value_counts())

# сохраняем результаты
results_implicit = add_results(results_implicit, "NNM_ItemItemRecomender_Optuna", elapsed_time, p_at_k_train, p_at_k)
display(results_implicit)

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

Precision@3: 0.0730 Параметры модели: {'K': 46}

   visitorid  itemid         score  already_liked
0     197729   27442  3.630142e+07           True
1     197729    5730  2.174475e+07           True
2     197729  164400  2.040054e+07           True

Соответсвие itemid между рекомендациями и фактом {164400, 27442, 5730}

already_liked
True    3
Name: count, dtype: int64

                           Model      Time train_Precision@3 test_Precision@3
0            NNM_CosinRecomender  4.854386                 0         0.051156
1     NNM_CosinRecomender_Optuna  5.049159                 0         0.052387
2         NNM_ItemItemRecomender  4.798687                 0         0.071307
3  NNM_ItemItemRecomender_Optuna  5.474812                 0         0.072997

### 2.3. Модель `BM25Recommender`

**Модель `BM25Recommender`** из библиотеки Implicit использует алгоритм BM25 (Best Match 25) для ранжирования элементов на основе их релевантности пользователям. Этот алгоритм изначально использовался в информационных поисковых системах, но оказался эффективным и в рекомендательных системах. Рассмотрим ключевые параметры этой модели и предложим разумные диапазоны значений для них.

#### Основные параметры модели BM25Recommender:
1. **K**: Количество ближайших соседей, которые используются для формирования рекомендаций. Этот параметр влияет на точность и разнообразие рекомендаций. Чем больше значение K, тем больше элементов будет рассматриваться для формирования рекомендаций, однако это может увеличить вычислительные затраты. **Рекомендуемые значения:** 5–50.
2. **K1**: Параметр, контролирующий степень сглаживания частотности термина. Чем выше значение K1, тем больше влияние имеет частота взаимодействий. **Рекомендуемые значения:** 1.2–2.0.
3. **B**: Параметр, управляющий весом длины документа. В данном случае, это будет влиять на длину списка взаимодействий каждого пользователя. При меньших значениях B короткие списки будут иметь больший вес относительно длинных списков. **Рекомендуемые значения:** 0.75–0.9.
4. **num_threads**: Количество потоков, используемых для параллельных вычислений. Этот параметр важен для увеличения скорости обработки больших наборов данных. **Рекомендуемые значения:** зависит от количества ядер процессора, обычно 1–8.

In [13]:
# фиксируем время начала работы
start_time = time.time()
# формируем параметры модели и обучаем её
model = BM25Recommender(
    K=11,               # Увеличим количество ближайших соседей для большей точности
    K1=0.2,             # Установим среднее значение для контроля частотности
    B=0.1,              # Средний вес для управления длиной списка взаимодействий
    num_threads=8       # Используем несколько потоков для ускорения
)

model.fit(train)

# расчитываем метрику precision@k
p_at_k = precision_at_k(model, train, test, K=3)
p_at_k_train = 0
# фиксируем время окончания работы
end_time = time.time()
elapsed_time = end_time - start_time

print(f'Precision@3: {p_at_k:.4f}')
print()
# Вариан 1 - Выбираем случайного пользователя
random_normalized_visitorid = np.random.choice(users)

# Вариант 2 - Вводим оригинальный visitorid
# original_visitorid = 391657
# random_normalized_visitorid = original_visitorid - min_visitorid # приводим его к нормализованному виду

userid = user_to_idx[random_normalized_visitorid]

# получаем рекомендации для пользователя
ids, scores = model.recommend(userid, matrix[userid], N=3, filter_already_liked_items=False)
# преобразуем обратно в оригинальные itemid
original_item_ids = [items[idx] + min_itemid for idx in ids]
# преобразуем обратно в оригинальный visitorid
original_visitorid = random_normalized_visitorid + min_visitorid

# используем pandas для отображения результатов в виде таблицы
rec_user = pd.DataFrame({
    "visitorid": original_visitorid,
    "itemid": original_item_ids,
    "score": scores,
    "already_liked": np.in1d(ids, matrix[userid].indices.ravel())  # преобразуем в одномерный массив
})
print(rec_user)
print()
set1 = set(df[df["visitorid"] == original_visitorid]["itemid"].unique().tolist())
set2 = set(original_item_ids)
print(f'Соответсвие itemid между рекомендациями и фактом {set1&set2}')
print()
print(rec_user["already_liked"].value_counts())
print()

# сохраняем результаты
results_implicit = add_results(results_implicit, "NNM_BM25Recomender", elapsed_time, p_at_k_train, p_at_k)
display(results_implicit)

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

Precision@3: 0.1256

   visitorid  itemid          score  already_liked
0    1047011  414605  166355.912515           True
1    1047011  165429   86280.837714           True
2    1047011   40140   37870.007292          False

Соответсвие itemid между рекомендациями и фактом {165429, 414605}

already_liked
True     2
False    1
Name: count, dtype: int64

                           Model      Time train_Precision@3 test_Precision@3
0            NNM_CosinRecomender  4.854386                 0         0.051156
1     NNM_CosinRecomender_Optuna  5.049159                 0         0.052387
2         NNM_ItemItemRecomender  4.798687                 0         0.071307
3  NNM_ItemItemRecomender_Optuna  5.474812                 0         0.072997
4             NNM_BM25Recomender   4.87209                 0         0.125621

### Подбор гиперпараметров с помощью **OPTUNA**

In [14]:
%%time
def objective(trial):
    # Получаем гиперпараметры из trial
    K = trial.suggest_int('K', 1, 500)
    K1 = trial.suggest_float('K1', low=0.1, high=1, step=0.01)
    B = trial.suggest_float('B', low=0.01, high=0.3, step=0.001)
    
    # Обучаем модель с новыми параметрами
    model = BM25Recommender(
        K=K,
        K1=K1,
        B=B,
        num_threads=8
    )
    
    model.fit(train)

    # Оцениваем модель
    p_at_k = precision_at_k(model, train, test, K=3)
    
    return p_at_k

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50, show_progress_bar=True)

best_params = study.best_trial.params
print("Лучшие параметры:", best_params)

[I 2025-01-17 13:49:07,180] A new study created in memory with name: no-name-978d5606-e4fd-4abb-b812-540b7acbc2bd

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:49:12,489] Trial 0 finished with value: 0.13100339556056406 and parameters: {'K': 67, 'K1': 0.13, 'B': 0.29700000000000004}. Best is trial 0 with value: 0.13100339556056406.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:49:20,612] Trial 1 finished with value: 0.13149271214839636 and parameters: {'K': 335, 'K1': 0.13, 'B': 0.29100000000000004}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:49:28,310] Trial 2 finished with value: 0.1302323512403434 and parameters: {'K': 358, 'K1': 0.62, 'B': 0.272}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:49:35,569] Trial 3 finished with value: 0.13024717901573227 and parameters: {'K': 320, 'K1': 0.61, 'B': 0.166}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:49:42,075] Trial 4 finished with value: 0.1306623567266203 and parameters: {'K': 228, 'K1': 0.37, 'B': 0.14400000000000002}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:49:51,272] Trial 5 finished with value: 0.12990614018178853 and parameters: {'K': 464, 'K1': 1.0, 'B': 0.231}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:49:57,654] Trial 6 finished with value: 0.13039545676962086 and parameters: {'K': 218, 'K1': 0.58, 'B': 0.169}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:50:03,034] Trial 7 finished with value: 0.12972820687712222 and parameters: {'K': 96, 'K1': 0.8, 'B': 0.197}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:50:09,380] Trial 8 finished with value: 0.13063270117584258 and parameters: {'K': 187, 'K1': 0.30000000000000004, 'B': 0.18200000000000002}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:50:15,484] Trial 9 finished with value: 0.13009890126184367 and parameters: {'K': 183, 'K1': 0.24000000000000002, 'B': 0.074}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:50:24,370] Trial 10 finished with value: 0.1297726902032888 and parameters: {'K': 484, 'K1': 0.41000000000000003, 'B': 0.016}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:50:29,214] Trial 11 finished with value: 8.896665233315046e-05 and parameters: {'K': 1, 'K1': 0.11, 'B': 0.29500000000000004}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:50:36,591] Trial 12 finished with value: 0.13122581219139692 and parameters: {'K': 346, 'K1': 0.1, 'B': 0.253}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:50:44,291] Trial 13 finished with value: 0.13115167331445263 and parameters: {'K': 352, 'K1': 0.21000000000000002, 'B': 0.24500000000000002}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:50:52,748] Trial 14 finished with value: 0.1308847733574532 and parameters: {'K': 420, 'K1': 0.44000000000000006, 'B': 0.23700000000000002}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:51:00,243] Trial 15 finished with value: 0.13103305111134175 and parameters: {'K': 298, 'K1': 0.1, 'B': 0.107}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:51:08,396] Trial 16 finished with value: 0.1311961566406192 and parameters: {'K': 399, 'K1': 0.26, 'B': 0.261}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:51:15,814] Trial 17 finished with value: 0.1308106344805089 and parameters: {'K': 280, 'K1': 0.48, 'B': 0.21700000000000003}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:51:23,883] Trial 18 finished with value: 0.13032131789267656 and parameters: {'K': 410, 'K1': 0.75, 'B': 0.275}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:51:30,759] Trial 19 finished with value: 0.13092925668361977 and parameters: {'K': 262, 'K1': 0.33, 'B': 0.20900000000000002}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:51:38,274] Trial 20 finished with value: 0.13078097892973117 and parameters: {'K': 345, 'K1': 0.19, 'B': 0.124}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:51:46,405] Trial 21 finished with value: 0.13115167331445263 and parameters: {'K': 406, 'K1': 0.27, 'B': 0.265}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:51:54,247] Trial 22 finished with value: 0.13124063996678578 and parameters: {'K': 370, 'K1': 0.18, 'B': 0.251}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:52:02,586] Trial 23 finished with value: 0.13122581219139692 and parameters: {'K': 445, 'K1': 0.18, 'B': 0.25}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:52:10,472] Trial 24 finished with value: 0.13135926216989666 and parameters: {'K': 383, 'K1': 0.17, 'B': 0.29700000000000004}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:52:18,952] Trial 25 finished with value: 0.13086994558206433 and parameters: {'K': 379, 'K1': 0.49, 'B': 0.29300000000000004}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:52:27,842] Trial 26 finished with value: 0.13095891223439748 and parameters: {'K': 498, 'K1': 0.33999999999999997, 'B': 0.299}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:52:35,309] Trial 27 finished with value: 0.13121098441600806 and parameters: {'K': 305, 'K1': 0.18, 'B': 0.276}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:52:43,682] Trial 28 finished with value: 0.13011372903723253 and parameters: {'K': 438, 'K1': 0.7, 'B': 0.22}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:52:49,309] Trial 29 finished with value: 0.1310182233359529 and parameters: {'K': 134, 'K1': 0.17, 'B': 0.28500000000000003}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:52:56,755] Trial 30 finished with value: 0.12996545128334397 and parameters: {'K': 316, 'K1': 0.99, 'B': 0.198}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:53:04,412] Trial 31 finished with value: 0.13125546774217464 and parameters: {'K': 370, 'K1': 0.1, 'B': 0.253}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:53:12,451] Trial 32 finished with value: 0.13140374549606323 and parameters: {'K': 370, 'K1': 0.16, 'B': 0.27}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:53:20,363] Trial 33 finished with value: 0.13147788437300753 and parameters: {'K': 384, 'K1': 0.15000000000000002, 'B': 0.278}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:53:27,719] Trial 34 finished with value: 0.1313444343945078 and parameters: {'K': 336, 'K1': 0.24000000000000002, 'B': 0.274}. Best is trial 1 with value: 0.13149271214839636.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:53:35,915] Trial 35 finished with value: 0.13156685102534066 and parameters: {'K': 381, 'K1': 0.14, 'B': 0.28600000000000003}. Best is trial 35 with value: 0.13156685102534066.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:53:44,628] Trial 36 finished with value: 0.1310182233359529 and parameters: {'K': 453, 'K1': 0.39, 'B': 0.277}. Best is trial 35 with value: 0.13156685102534066.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:53:51,600] Trial 37 finished with value: 0.13115167331445263 and parameters: {'K': 246, 'K1': 0.29000000000000004, 'B': 0.232}. Best is trial 35 with value: 0.13156685102534066.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:53:58,611] Trial 38 finished with value: 0.13147788437300753 and parameters: {'K': 281, 'K1': 0.14, 'B': 0.28200000000000003}. Best is trial 35 with value: 0.13156685102534066.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:54:05,257] Trial 39 finished with value: 0.12972820687712222 and parameters: {'K': 219, 'K1': 0.9, 'B': 0.14500000000000002}. Best is trial 35 with value: 0.13156685102534066.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:54:12,419] Trial 40 finished with value: 0.13152236769917408 and parameters: {'K': 286, 'K1': 0.14, 'B': 0.28500000000000003}. Best is trial 35 with value: 0.13156685102534066.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:54:19,465] Trial 41 finished with value: 0.13122581219139692 and parameters: {'K': 264, 'K1': 0.22, 'B': 0.28800000000000003}. Best is trial 35 with value: 0.13156685102534066.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:54:26,821] Trial 42 finished with value: 0.13137408994528552 and parameters: {'K': 303, 'K1': 0.13, 'B': 0.28200000000000003}. Best is trial 35 with value: 0.13156685102534066.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:54:32,942] Trial 43 finished with value: 0.13018786791417683 and parameters: {'K': 186, 'K1': 0.13, 'B': 0.022}. Best is trial 35 with value: 0.13156685102534066.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:54:40,124] Trial 44 finished with value: 0.1311665010898415 and parameters: {'K': 284, 'K1': 0.33, 'B': 0.234}. Best is trial 35 with value: 0.13156685102534066.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:54:47,674] Trial 45 finished with value: 0.13067718450200916 and parameters: {'K': 328, 'K1': 0.23, 'B': 0.063}. Best is trial 35 with value: 0.13156685102534066.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:54:54,797] Trial 46 finished with value: 0.13140374549606323 and parameters: {'K': 285, 'K1': 0.14, 'B': 0.264}. Best is trial 35 with value: 0.13156685102534066.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:55:01,417] Trial 47 finished with value: 0.1312702955175635 and parameters: {'K': 241, 'K1': 0.27, 'B': 0.29800000000000004}. Best is trial 35 with value: 0.13156685102534066.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:55:09,157] Trial 48 finished with value: 0.1302323512403434 and parameters: {'K': 324, 'K1': 0.61, 'B': 0.261}. Best is trial 35 with value: 0.13156685102534066.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:55:17,368] Trial 49 finished with value: 0.13118132886523035 and parameters: {'K': 427, 'K1': 0.21000000000000002, 'B': 0.24100000000000002}. Best is trial 35 with value: 0.13156685102534066.
Лучшие параметры: {'K': 381, 'K1': 0.14, 'B': 0.28600000000000003}
CPU times: user 8min 5s, sys: 1min 35s, total: 9min 41s
Wall time: 6min 10s

In [15]:
# визуализация среза
optuna.visualization.plot_slice(study, target_name="p_at_k")

In [16]:
# фиксируем время начала работы
start_time = time.time()
# формируем параметры модели и обучаем её с учетом подобранных параметров
model = BM25Recommender(**best_params, 
                        num_threads=8)


model.fit(train)

# расчитываем метрику precision@k
p_at_k = precision_at_k(model, train, test, K=3)
p_at_k_train = 0
# фиксируем время окончания работы
end_time = time.time()
elapsed_time = end_time - start_time

print(f'Precision@3: {p_at_k:.4f}', f'Параметры модели: {best_params}')
print()
# Вариан 1 - Выбираем случайного пользователя
random_normalized_visitorid = np.random.choice(users)

# Вариант 2 - Вводим оригинальный visitorid
# original_visitorid = 391657
# random_normalized_visitorid = original_visitorid - min_visitorid # приводим его к нормализованному виду

userid = user_to_idx[random_normalized_visitorid]

# получаем рекомендации для пользователя
ids, scores = model.recommend(userid, matrix[userid], N=3, filter_already_liked_items=False)
# преобразуем обратно в оригинальные itemid
original_item_ids = [items[idx] + min_itemid for idx in ids]
# преобразуем обратно в оригинальный visitorid
original_visitorid = random_normalized_visitorid + min_visitorid

# используем pandas для отображения результатов в виде таблицы
rec_user = pd.DataFrame({
    "visitorid": original_visitorid,
    "itemid": original_item_ids,
    "score": scores,
    "already_liked": np.in1d(ids, matrix[userid].indices.ravel())  # преобразуем в одномерный массив
})
print(rec_user)
print()
set1 = set(df[df["visitorid"] == original_visitorid]["itemid"].unique().tolist())
set2 = set(original_item_ids)
print(f'Соответсвие itemid между рекомендациями и фактом {set1&set2}')
print()
print(rec_user["already_liked"].value_counts())

# сохраняем результаты
results_implicit = add_results(results_implicit, "NNM_BM25Recomender_Optuna", elapsed_time, p_at_k_train, p_at_k)
display(results_implicit)

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

Precision@3: 0.1316 Параметры модели: {'K': 381, 'K1': 0.14, 'B': 0.28600000000000003}

   visitorid  itemid          score  already_liked
0     631166  141240  250097.735444           True
1     631166  286044  199173.894489           True
2     631166  165161  155352.110214           True

Соответсвие itemid между рекомендациями и фактом {141240, 165161, 286044}

already_liked
True    3
Name: count, dtype: int64

                           Model      Time train_Precision@3 test_Precision@3
0            NNM_CosinRecomender  4.854386                 0         0.051156
1     NNM_CosinRecomender_Optuna  5.049159                 0         0.052387
2         NNM_ItemItemRecomender  4.798687                 0         0.071307
3  NNM_ItemItemRecomender_Optuna  5.474812                 0         0.072997
4             NNM_BM25Recomender   4.87209                 0         0.125621
5      NNM_BM25Recomender_Optuna  8.314192                 0         0.131567

## 3. Построение моделей на базе алгоритмов "Матричной факторизации и факторизационных машин."

***Матричная факторизация и факторизационные машины*** — это мощные инструменты, которые используются в рекомендательных системах (РС) для предсказания предпочтений пользователей на основе их прошлого поведения. Давайте разберём оба этих понятия отдельно.

### Матричная факторизация (Matrix Factorization)

**Матричная факторизация** — это метод, который пытается найти скрытую структуру в данных, представленных в виде матрицы. В контексте рекомендательных систем, эта матрица обычно содержит рейтинги или взаимодействия пользователей с объектами (например, фильмы, песни, товары). Цель матричной факторизации — представить эту большую и зачастую разреженную матрицу в виде произведения двух меньших матриц, которые содержат скрытые факторы (латентные переменные).

#### Как это работает?

Предположим, у нас есть матрица $R$ размером $m \times n$, где $m$ — количество пользователей, а $n$ — количество объектов. Мы хотим разложить эту матрицу на два фактора: матрицу $P$ размером $m \times k$ и матрицу $Q$ размером $k \times n$. Здесь $k$ — это количество скрытых факторов, которые мы выбираем заранее.

Процесс выглядит так:

$$ R \approx P \cdot Q^T

$$

Где $Q^T$ — транспонированная матрица $Q$.

#### Что означают эти скрытые факторы?

Скрытые факторы представляют собой абстрактные характеристики, которые объясняют предпочтения пользователей и свойства объектов. Например, в случае рекомендательной системы фильмов, эти факторы могут включать жанры, актёров, режиссеров и т.д. Пользователи и объекты могут быть описаны в терминах этих факторов, что позволяет системе находить соответствия между ними.

#### Почему это полезно?

Матричная факторизация позволяет уменьшить размерность данных, что делает расчёты быстрее и эффективнее. Кроме того, она помогает справиться с проблемой разреженности данных, так как заполняет пропущенные значения в матрице рейтингов на основе найденных скрытых факторов.

### Факторизационные машины (Factorization Machines)

**Факторизационные машины (FM)** — это расширение идеи матричной факторизации, которое было предложено Штейнером и Фридманом в 2010 году. В отличие от обычной матричной факторизации, которая рассматривает только пары взаимодействий (пользователь-объект), факторизационные машины также учитывают взаимодействия между различными признаками.

#### Как это работает?

Факторизационная машина принимает на вход вектор признаков $x$ и вычисляет предсказанное значение $y$ следующим образом:

$$ \hat{y}(x) = w_0 + \sum_{i=1}^n w_i x_i + \sum_{i=1}^n \sum_{j=i+1}^n \langle v_i, v_j \rangle x_i x_j

$$

Здесь:
- $w_0$ — глобальный сдвиг,
- $w_i$ — вес признака $i$,
- $v_i$ и $v_j$ — векторы скрытых факторов для признаков $i$ и $j$,
- $\langle v_i, v_j \rangle$ — скалярное произведение векторов $v_i$ и $v_j$.

#### Зачем нужны взаимодействия признаков?

Взаимодействия признаков позволяют учитывать более сложные зависимости между разными аспектами данных. Например, в электронной коммерции взаимодействие между характеристиками товара и историей покупок пользователя может дать более точную картину его предпочтений, чем просто сумма отдельных характеристик.

#### Преимущества факторизационных машин:

- Учитываются взаимодействия между признаками, что приводит к более точным моделям.
- Хорошо справляются с разреженными данными, что делает их полезными в рекомендательных системах.
- Универсальны и могут применяться не только для задач классификации и регрессии, но и для задач ранжирования.

### Сравнение матричной факторизации и факторизационных машин:

- **Матричная факторизация** фокусируется на разбиении большой матрицы взаимодействий на две меньшие матрицы, содержащие скрытые факторы. Она проста в понимании и реализации, но ограничена парными взаимодействиями.
  
- **Факторизационные машины** идут дальше, учитывая взаимодействия между различными признаками, что делает их более мощными и гибкими. Они сложнее в реализации, но предлагают лучшую точность и универсальность.

Оба метода играют важную роль в рекомендательных системах, помогая создавать персонализированные рекомендации на основе истории взаимодействий пользователей с объектами.

### 3.1. Модель `AlternatingLeastSquares` (ALS)

**Модель `AlternatingLeastSquares` (ALS)** — это еще один популярный алгоритм для построения рекомендательных систем, основанная на факторизационных методах. Она широко применяется благодаря своей эффективности и возможности масштабироваться на большие наборы данных. Рассмотрим ключевые параметры этой модели и предложим разумные диапазоны значений для них.

#### Основные параметры модели ALS:

1. **factors**: Количество скрытых факторов, используемых для представления пользователей и товаров. Этот параметр влияет на сложность модели. Обычно его выбирают в диапазоне от 50 до 300, хотя иногда используют и большие значения, если требуется высокая точность. **Рекомендуемые значения:** 50–200
2. **regularization**: Регуляризация предотвращает переобучение модели, добавляя штраф за сложность параметров. Высокие значения регуляризации могут ухудшить способность модели обобщать новые данные, низкие — приведут к переобучению. **Рекомендуемые значения:** 0.01–0.1
3. **alpha**: Этот параметр используется для вычисления взвешенных оценок. Он добавляет дополнительный вес позитивным примерам (например, купленным товарам) по сравнению с негативными (некупленными). **Рекомендуемые значения:** 1–40
4. **iterations**: Количество эпох обучения. Определяет, сколько раз модель пройдет через весь набор данных. Обычно выбирается в зависимости от размера набора данных и сложности задачи. **Рекомендуемые значения:** 10–30
5. **use_cg**: Использование метода сопряжённых градиентов для оптимизации. Может ускорить процесс обучения, но требует больше памяти. **Рекомендуемые значения:** True или False
6. **calculate_training_loss**: Включает расчет потерь на этапе обучения. Полезно для мониторинга процесса обучения. **Рекомендуемые значения:** True или False

In [17]:
# фиксируем время начала работы
start_time = time.time()
# формируем параметры модели и обучаем её
model = AlternatingLeastSquares(
    factors=100,                   # Увеличим количество факторов для повышения точности
    regularization=0.01,           # Среднее значение регуляризации
    alpha=1,                       # Добавляем умеренное смещение к позитивным примерам
    iterations=15,                 # Разумное количество итераций
    use_native=True,
    use_cg=True,                   # Используем метод сопряжённых градиентов
    calculate_training_loss=False, # Рассчитываем потери на этапе обучения
    random_state=RANDOM_SEED,
    num_threads=8
)

model.fit(train)

# расчитываем метрику precision@k
p_at_k = precision_at_k(model, train, test, K=3)
p_at_k_train = 0
# фиксируем время окончания работы
end_time = time.time()
elapsed_time = end_time - start_time

print(f'Precision@3: {p_at_k:.4f}')
print()
# Вариан 1 - Выбираем случайного пользователя
random_normalized_visitorid = np.random.choice(users)

# Вариант 2 - Вводим оригинальный visitorid
# original_visitorid = 391657
# random_normalized_visitorid = original_visitorid - min_visitorid # приводим его к нормализованному виду

userid = user_to_idx[random_normalized_visitorid]

# получаем рекомендации для пользователя
ids, scores = model.recommend(userid, matrix[userid], N=3, filter_already_liked_items=False)
# преобразуем обратно в оригинальные itemid
original_item_ids = [items[idx] + min_itemid for idx in ids]
# преобразуем обратно в оригинальный visitorid
original_visitorid = random_normalized_visitorid + min_visitorid

# используем pandas для отображения результатов в виде таблицы
rec_user = pd.DataFrame({
    "visitorid": original_visitorid,
    "itemid": original_item_ids,
    "score": scores,
    "already_liked": np.in1d(ids, matrix[userid].indices.ravel())  # преобразуем в одномерный массив
})
print(rec_user)
print()
set1 = set(df[df["visitorid"] == original_visitorid]["itemid"].unique().tolist())
set2 = set(original_item_ids)
print(f'Соответсвие itemid между рекомендациями и фактом {set1&set2}')
print()
print(rec_user["already_liked"].value_counts())
print()

# сохраняем результаты
results_implicit = add_results(results_implicit, "MF_ALS", elapsed_time, p_at_k_train, p_at_k)
display(results_implicit)

  0%|          | 0/15 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

Precision@3: 0.0846

   visitorid  itemid     score  already_liked
0    1093088  232172  0.431954           True
1    1093088   88098  0.403144          False
2    1093088  400946  0.398671          False

Соответсвие itemid между рекомендациями и фактом {232172}

already_liked
False    2
True     1
Name: count, dtype: int64

                           Model       Time train_Precision@3 test_Precision@3
0            NNM_CosinRecomender   4.854386                 0         0.051156
1     NNM_CosinRecomender_Optuna   5.049159                 0         0.052387
2         NNM_ItemItemRecomender   4.798687                 0         0.071307
3  NNM_ItemItemRecomender_Optuna   5.474812                 0         0.072997
4             NNM_BM25Recomender    4.87209                 0         0.125621
5      NNM_BM25Recomender_Optuna   8.314192                 0         0.131567
6                         MF_ALS  21.649938                 0         0.084578

#### Подбор гиперпараметров с помощью **OPTUNA**

In [18]:
def objective(trial):
    # Получаем гиперпараметры из trial
    factors = trial.suggest_int("factors", 50, 200)
    regularization = trial.suggest_loguniform("regularization", 1e-4, 1e-1)
    alpha = trial.suggest_uniform("alpha", 0.5, 10)
    use_native = trial.suggest_categorical("use_native", ["False", "True"])
    use_cg = trial.suggest_categorical("use_cg", ["False", "True"])
    calculate_traning_loss = trial.suggest_categorical("calculate_training_loss", ["False", "True"])
    
    # Формируем и обучаем модель с новыми параметрами
    model = AlternatingLeastSquares(
        factors=factors,
        regularization=regularization,
        alpha=alpha,
        iterations=20,
        use_native=use_native,
        use_cg=use_cg,
        calculate_training_loss=calculate_traning_loss,
        random_state=RANDOM_SEED,
        num_threads=8
    )
    model.fit(train)

    # Оцениваем модель
    p_at_k = precision_at_k(model, train, test, K=3)
    
    return p_at_k

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=10, show_progress_bar=True)

best_params = study.best_trial.params
print("Лучшие параметры:", best_params)

[I 2025-01-17 13:56:54,729] A new study created in memory with name: no-name-97f7235b-14ce-4749-9cf9-02d11275a4ee

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:57:25,654] Trial 0 finished with value: 0.10237096128467846 and parameters: {'factors': 136, 'regularization': 0.005673797179418088, 'alpha': 9.75834753811319, 'use_native': 'False', 'use_cg': 'False', 'calculate_training_loss': 'True'}. Best is trial 0 with value: 0.10237096128467846.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:58:04,708] Trial 1 finished with value: 0.09311842944203082 and parameters: {'factors': 134, 'regularization': 0.0001046877301557195, 'alpha': 2.8953163852848425, 'use_native': 'False', 'use_cg': 'False', 'calculate_training_loss': 'False'}. Best is trial 0 with value: 0.10237096128467846.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:58:40,931] Trial 2 finished with value: 0.08760249699737549 and parameters: {'factors': 76, 'regularization': 0.0006788329085309125, 'alpha': 9.907655357291256, 'use_native': 'False', 'use_cg': 'False', 'calculate_training_loss': 'True'}. Best is trial 0 with value: 0.10237096128467846.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:59:17,051] Trial 3 finished with value: 0.09514983467030441 and parameters: {'factors': 104, 'regularization': 0.0015347532655482403, 'alpha': 8.129953542567833, 'use_native': 'False', 'use_cg': 'True', 'calculate_training_loss': 'False'}. Best is trial 0 with value: 0.10237096128467846.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 13:59:57,482] Trial 4 finished with value: 0.10115508370279207 and parameters: {'factors': 151, 'regularization': 0.01954982981433817, 'alpha': 5.101282176555058, 'use_native': 'False', 'use_cg': 'False', 'calculate_training_loss': 'True'}. Best is trial 0 with value: 0.10237096128467846.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:00:37,342] Trial 5 finished with value: 0.08778043030204179 and parameters: {'factors': 136, 'regularization': 0.04500292620346854, 'alpha': 1.0607890795068133, 'use_native': 'True', 'use_cg': 'True', 'calculate_training_loss': 'False'}. Best is trial 0 with value: 0.10237096128467846.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:01:19,261] Trial 6 finished with value: 0.1057072107471716 and parameters: {'factors': 171, 'regularization': 0.001099998975114842, 'alpha': 6.829588981283846, 'use_native': 'True', 'use_cg': 'False', 'calculate_training_loss': 'False'}. Best is trial 6 with value: 0.1057072107471716.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:01:59,234] Trial 7 finished with value: 0.09906436737296304 and parameters: {'factors': 119, 'regularization': 0.024471329767163128, 'alpha': 9.468868128139807, 'use_native': 'True', 'use_cg': 'True', 'calculate_training_loss': 'False'}. Best is trial 6 with value: 0.1057072107471716.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:02:40,815] Trial 8 finished with value: 0.09710710102163372 and parameters: {'factors': 131, 'regularization': 0.0029247546224749075, 'alpha': 4.7537799290361855, 'use_native': 'False', 'use_cg': 'True', 'calculate_training_loss': 'False'}. Best is trial 6 with value: 0.1057072107471716.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:03:19,413] Trial 9 finished with value: 0.08861078572381785 and parameters: {'factors': 79, 'regularization': 0.00019240834430345083, 'alpha': 9.975925977787659, 'use_native': 'True', 'use_cg': 'False', 'calculate_training_loss': 'False'}. Best is trial 6 with value: 0.1057072107471716.
Лучшие параметры: {'factors': 171, 'regularization': 0.001099998975114842, 'alpha': 6.829588981283846, 'use_native': 'True', 'use_cg': 'False', 'calculate_training_loss': 'False'}

In [19]:
# визуализация среза
optuna.visualization.plot_slice(study, target_name="p_at_k")

In [20]:
# фиксируем время начала работы
start_time = time.time()
# формируем параметры модели и обучаем её
model = AlternatingLeastSquares(**best_params, 
                                iterations=30, 
                                random_state=RANDOM_SEED, 
                                num_threads=8)


model.fit(train)

# расчитываем метрику precision@k
p_at_k = precision_at_k(model, train, test, K=3)
p_at_k_train = 0
# фиксируем время окончания работы
end_time = time.time()
elapsed_time = end_time - start_time

print(f'Precision@3: {p_at_k:.4f}', f'Best params: {best_params}')
print()
# Вариан 1 - Выбираем случайного пользователя
random_normalized_visitorid = np.random.choice(users)

# Вариант 2 - Вводим оригинальный visitorid
# original_visitorid = 391657
# random_normalized_visitorid = original_visitorid - min_visitorid # приводим его к нормализованному виду

userid = user_to_idx[random_normalized_visitorid]

# получаем рекомендации для пользователя
ids, scores = model.recommend(userid, matrix[userid], N=3, filter_already_liked_items=False)
# преобразуем обратно в оригинальные itemid
original_item_ids = [items[idx] + min_itemid for idx in ids]
# преобразуем обратно в оригинальный visitorid
original_visitorid = random_normalized_visitorid + min_visitorid

# используем pandas для отображения результатов в виде таблицы
rec_user = pd.DataFrame({
    "visitorid": original_visitorid,
    "itemid": original_item_ids,
    "score": scores,
    "already_liked": np.in1d(ids, matrix[userid].indices.ravel())  # преобразуем в одномерный массив
})
print(rec_user)
print()
set1 = set(df[df["visitorid"] == original_visitorid]["itemid"].unique().tolist())
set2 = set(original_item_ids)
print(f'Соответсвие itemid между рекомендациями и фактом {set1&set2}')
print()
print(rec_user["already_liked"].value_counts())
print()

# сохраняем результаты
results_implicit = add_results(results_implicit, "MF_ALS_Optuna", elapsed_time, p_at_k_train, p_at_k)
display(results_implicit)

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

Precision@3: 0.1033 Best params: {'factors': 171, 'regularization': 0.001099998975114842, 'alpha': 6.829588981283846, 'use_native': 'True', 'use_cg': 'False', 'calculate_training_loss': 'False'}

   visitorid  itemid     score  already_liked
0     413313   16344  0.909082           True
1     413313  349470  0.747627          False
2     413313  303229  0.744699          False

Соответсвие itemid между рекомендациями и фактом {16344}

already_liked
False    2
True     1
Name: count, dtype: int64

                           Model       Time train_Precision@3 test_Precision@3
0            NNM_CosinRecomender   4.854386                 0         0.051156
1     NNM_CosinRecomender_Optuna   5.049159                 0         0.052387
2         NNM_ItemItemRecomender   4.798687                 0         0.071307
3  NNM_ItemItemRecomender_Optuna   5.474812                 0         0.072997
4             NNM_BM25Recomender    4.87209                 0         0.125621
5      NNM_BM25Recomender_Optuna   8.314192                 0         0.131567
6                         MF_ALS  21.649938                 0         0.084578
7                  MF_ALS_Optuna  52.817272                 0          0.10329

### 3.2. Модель `BayesianPersonalizedRanking` (BPR)

Модель **`BayesianPersonalizedRanking` (BPR)** — это популярный подход для обучения рекомендательных систем, основанный на байесовской персонализации. Она учитывает предпочтения пользователей и предлагает им персонализированные рекомендации. Давайте рассмотрим ключевые параметры этой модели и предложим разумные диапазоны значений для них.

### Основные параметры модели BPR:

1. **factors**: Количество скрытых факторов, используемых для представления пользователей и товаров. Этот параметр влияет на сложность модели. Обычно его выбирают в диапазоне от 50 до 200, хотя иногда используют и большие значения, такие как 500, если требуется высокая точность. **Рекомендуемые значения:** 50–200.
2. **learning_rate**: Скорость обучения определяет, насколько быстро модель обновляет свои параметры на каждой итерации. Слишком большая скорость может привести к тому, что модель не сойдется, слишком маленькая — замедлит обучение. **Рекомендуемые значения:** 0.001–0.01.
3. **regularization**: Регуляризация предотвращает переобучение модели, добавляя штраф за сложность параметров. Высокие значения регуляризации могут ухудшить способность модели обобщать новые данные, низкие — приведут к переобучению. **Рекомендуемые значения:** 0.02–0.2.
4. **iterations**: Количество эпох обучения. Определяет, сколько раз модель пройдет через весь набор данных. Обычно выбирается в зависимости от размера набора данных и сложности задачи. **Рекомендуемые значения:** 10–30.
5. **random_state**: Используется для инициализации генератора случайных чисел. Важно фиксировать это значение для воспроизводимости экспериментов. **Рекомендуемый диапазон:** любое целое число.

In [21]:
# фиксируем время начала работы
start_time = time.time()
# формируем параметры модели и обучаем её
model = BayesianPersonalizedRanking(
    factors=100,                     # Уменьшаем количество факторов для ускорения обучения
    learning_rate=0.01,              # Увеличиваем скорость обучения для лучшего сходимости
    regularization=0.01,             # Средний уровень регуляризации
    iterations=100,                  # Устанавливаем разумное количество итераций
    random_state=RANDOM_SEED,        # Фиксируем состояние генератора случайных чисел
    num_threads=8,                   # Устанавливаем количество потоков для обучения
)

model.fit(train)

# расчитываем метрику precision@k
p_at_k = precision_at_k(model, train, test, K=3)
p_at_k_train = 0
# фиксируем время окончания работы
end_time = time.time()
elapsed_time = end_time - start_time

print(f'Precision@3: {p_at_k:.4f}')
print()
# Вариан 1 - Выбираем случайного пользователя
random_normalized_visitorid = np.random.choice(users)

# Вариант 2 - Вводим оригинальный visitorid
# original_visitorid = 391657
# random_normalized_visitorid = original_visitorid - min_visitorid # приводим его к нормализованному виду

userid = user_to_idx[random_normalized_visitorid]

# получаем рекомендации для пользователя
ids, scores = model.recommend(userid, matrix[userid], N=3, filter_already_liked_items=False)
# преобразуем обратно в оригинальные itemid
original_item_ids = [items[idx] + min_itemid for idx in ids]
# преобразуем обратно в оригинальный visitorid
original_visitorid = random_normalized_visitorid + min_visitorid

# используем pandas для отображения результатов в виде таблицы
rec_user = pd.DataFrame({
    "visitorid": original_visitorid,
    "itemid": original_item_ids,
    "score": scores,
    "already_liked": np.in1d(ids, matrix[userid].indices.ravel())  # преобразуем в одномерный массив
})
print(rec_user)
print()
set1 = set(df[df["visitorid"] == original_visitorid]["itemid"].unique().tolist())
set2 = set(original_item_ids)
print(f'Соответсвие itemid между рекомендациями и фактом {set1&set2}')
print()
print(rec_user["already_liked"].value_counts())
print()

# сохраняем результаты
results_implicit = add_results(results_implicit, "MF_BPR", elapsed_time, p_at_k_train, p_at_k)
display(results_implicit)

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

Precision@3: 0.0247

   visitorid  itemid     score  already_liked
0    1267708    5411  1.302400          False
1    1267708  440248  1.223577           True
2    1267708  233938  1.128510          False

Соответсвие itemid между рекомендациями и фактом {440248}

already_liked
False    2
True     1
Name: count, dtype: int64

                           Model       Time train_Precision@3 test_Precision@3
0            NNM_CosinRecomender   4.854386                 0         0.051156
1     NNM_CosinRecomender_Optuna   5.049159                 0         0.052387
2         NNM_ItemItemRecomender   4.798687                 0         0.071307
3  NNM_ItemItemRecomender_Optuna   5.474812                 0         0.072997
4             NNM_BM25Recomender    4.87209                 0         0.125621
5      NNM_BM25Recomender_Optuna   8.314192                 0         0.131567
6                         MF_ALS  21.649938                 0         0.084578
7                  MF_ALS_Optuna  52.817272                 0          0.10329
8                         MF_BPR  25.006213                 0         0.024703

#### Подбор гиперпараметров с помощью **OPTUNA**

In [22]:
def objective(trial):
    # Получаем гиперпараметры из trial
    factors = trial.suggest_int("factors", 50, 200)
    regularization = trial.suggest_loguniform("regularization", 1e-4, 1e-1)
    learning_rate = trial.suggest_uniform("learning_rate", 1e-4, 1e-1)
    
    # Формируем и обучаем модель с новыми параметрами
    model = BayesianPersonalizedRanking(
        factors=factors,
        regularization=regularization,
        learning_rate=learning_rate,
        iterations=20,
        random_state=RANDOM_SEED,
        num_threads=8
    )
    model.fit(train)

    # Оцениваем модель
    p_at_k = precision_at_k(model, train, test, K=3)
    
    return p_at_k

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=10, show_progress_bar=True)

best_params = study.best_trial.params
print("Лучшие параметры:", best_params)

[I 2025-01-17 14:05:45,393] A new study created in memory with name: no-name-c32a7046-c5f9-45d4-9c3e-3d5a56ac734a

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:06:03,029] Trial 0 finished with value: 0.03625391082575881 and parameters: {'factors': 199, 'regularization': 0.0001707886658074546, 'learning_rate': 0.09551669181087513}. Best is trial 0 with value: 0.03625391082575881.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:06:21,588] Trial 1 finished with value: 0.02004715232573657 and parameters: {'factors': 175, 'regularization': 0.0001717767291832688, 'learning_rate': 0.046616266596851946}. Best is trial 0 with value: 0.03625391082575881.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:06:39,861] Trial 2 finished with value: 5.931110155543364e-05 and parameters: {'factors': 143, 'regularization': 0.07037480213055064, 'learning_rate': 0.032699349941034225}. Best is trial 0 with value: 0.03625391082575881.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:07:02,762] Trial 3 finished with value: 0.003692116071825744 and parameters: {'factors': 197, 'regularization': 0.00028897831379507116, 'learning_rate': 0.02446791714323174}. Best is trial 0 with value: 0.03625391082575881.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:07:20,720] Trial 4 finished with value: 0.0010972553787755223 and parameters: {'factors': 75, 'regularization': 0.007469581040825004, 'learning_rate': 0.016603949665616024}. Best is trial 0 with value: 0.03625391082575881.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:07:39,341] Trial 5 finished with value: 0.010957726012366364 and parameters: {'factors': 165, 'regularization': 0.0001352163238073475, 'learning_rate': 0.033304332375786866}. Best is trial 0 with value: 0.03625391082575881.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:07:56,573] Trial 6 finished with value: 0.0002668999569994514 and parameters: {'factors': 81, 'regularization': 0.0918638282869709, 'learning_rate': 0.04980534194721003}. Best is trial 0 with value: 0.03625391082575881.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:08:16,750] Trial 7 finished with value: 0.0008451831971649294 and parameters: {'factors': 189, 'regularization': 0.001937099447425308, 'learning_rate': 0.012305219359928043}. Best is trial 0 with value: 0.03625391082575881.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:08:35,053] Trial 8 finished with value: 0.02227131863406533 and parameters: {'factors': 135, 'regularization': 0.007581695994597397, 'learning_rate': 0.056664658027250105}. Best is trial 0 with value: 0.03625391082575881.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:08:57,195] Trial 9 finished with value: 0.009934609510535134 and parameters: {'factors': 194, 'regularization': 0.004931425277400491, 'learning_rate': 0.034438057072984016}. Best is trial 0 with value: 0.03625391082575881.
Лучшие параметры: {'factors': 199, 'regularization': 0.0001707886658074546, 'learning_rate': 0.09551669181087513}

In [23]:
# визуализация среза
optuna.visualization.plot_slice(study, target_name="p_at_k")

In [24]:
# фиксируем время начала работы
start_time = time.time()
# формируем параметры модели и обучаем её
model = BayesianPersonalizedRanking(**best_params, 
                                    iterations=100, 
                                    random_state=RANDOM_SEED, 
                                    num_threads=8)

model.fit(train)

# расчитываем метрику precision@k
p_at_k = precision_at_k(model, train, test, K=3)
p_at_k_train = 0
# фиксируем время окончания работы
end_time = time.time()
elapsed_time = end_time - start_time

print(f'Precision@3: {p_at_k:.4f}')
print()
# Вариан 1 - Выбираем случайного пользователя
random_normalized_visitorid = np.random.choice(users)

# Вариант 2 - Вводим оригинальный visitorid
# original_visitorid = 391657
# random_normalized_visitorid = original_visitorid - min_visitorid # приводим его к нормализованному виду

userid = user_to_idx[random_normalized_visitorid]

# получаем рекомендации для пользователя
ids, scores = model.recommend(userid, matrix[userid], N=3, filter_already_liked_items=False)
# преобразуем обратно в оригинальные itemid
original_item_ids = [items[idx] + min_itemid for idx in ids]
# преобразуем обратно в оригинальный visitorid
original_visitorid = random_normalized_visitorid + min_visitorid

# используем pandas для отображения результатов в виде таблицы
rec_user = pd.DataFrame({
    "visitorid": original_visitorid,
    "itemid": original_item_ids,
    "score": scores,
    "already_liked": np.in1d(ids, matrix[userid].indices.ravel())  # преобразуем в одномерный массив
})
print(rec_user)
print()
set1 = set(df[df["visitorid"] == original_visitorid]["itemid"].unique().tolist())
set2 = set(original_item_ids)
print(f'Соответсвие itemid между рекомендациями и фактом {set1&set2}')
print()
print(rec_user["already_liked"].value_counts())
print()
# сохраняем результаты
results_implicit = add_results(results_implicit, "MF_BPR_Optuna", elapsed_time, p_at_k_train, p_at_k)
display(results_implicit)

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

Precision@3: 0.0607

   visitorid  itemid     score  already_liked
0     647768   12765  6.772482           True
1     647768  255725  6.672625           True
2     647768  177152  5.798221          False

Соответсвие itemid между рекомендациями и фактом {12765, 255725}

already_liked
True     2
False    1
Name: count, dtype: int64

                           Model       Time train_Precision@3 test_Precision@3
0            NNM_CosinRecomender   4.854386                 0         0.051156
1     NNM_CosinRecomender_Optuna   5.049159                 0         0.052387
2         NNM_ItemItemRecomender   4.798687                 0         0.071307
3  NNM_ItemItemRecomender_Optuna   5.474812                 0         0.072997
4             NNM_BM25Recomender    4.87209                 0         0.125621
5      NNM_BM25Recomender_Optuna   8.314192                 0         0.131567
6                         MF_ALS  21.649938                 0         0.084578
7                  MF_ALS_Optuna  52.817272                 0          0.10329
8                         MF_BPR  25.006213                 0         0.024703
9                  MF_BPR_Optuna  22.199291                 0          0.06069

### 3.3. Модель `LogisticMatrixFactorization`

Модель **`LogisticMatrixFactorization`** из библиотеки Implicit используется для факторизации логистической матрицы. Эта модель применяет логистический регрессор поверх факторизованной матрицы для предсказания вероятности взаимодействия пользователя с элементом. Рассмотрим ключевые параметры этой модели и предложим разумные диапазоны значений для них.

### Основные параметры модели LogisticMatrixFactorization:

1. **factors**: Количество скрытых факторов, используемых для представления пользователей и товаров. Этот параметр влияет на сложность модели. Обычно его выбирают в диапазоне от 50 до 300, хотя иногда используют и большие значения, если требуется высокая точность. **Рекомендуемые значения:** 50–200.
2. **regularization**: Регуляризация предотвращает переобучение модели, добавляя штраф за сложность параметров. Высокие значения регуляризации могут ухудшить способность модели обобщать новые данные, низкие — приведут к переобучению. **Рекомендуемые значения:** 0.01–0.1.
3. **iterations**: Количество эпох обучения. Определяет, сколько раз модель пройдет через весь набор данных. Обычно выбирается в зависимости от размера набора данных и сложности задачи. **Рекомендуемые значения:** 10–30.
4. **learning_rate**: Скорость обучения определяет, насколько быстро модель обновляет свои параметры на каждой итерации. Слишком большая скорость может привести к тому, что модель не сойдется, слишком маленькая — замедлит обучение. **Рекомендуемые значения:** 0.001–0.01. 
5. **random_state**: Используется для инициализации генератора случайных чисел. Важно фиксировать это значение для воспроизводимости экспериментов. **Рекомендуемый диапазон:** любое целое число.

In [25]:
# фиксируем время начала работы
start_time = time.time()
# формируем параметры модели и обучаем её
model = LogisticMatrixFactorization(
    factors=30,                 # Стандартное количество факторов
    regularization=0.6,         # Умеренная регуляризация
    iterations=30,              # Разумное количество итераций
    learning_rate=1.0,          # Средняя скорость обучения
    neg_prop=30,                # Количество негативных признаков
    random_state=RANDOM_SEED,   # Фиксированное состояние генератора случайных чисел
    num_threads=8,            # Количество потоков обучения
)

model.fit(train)

# расчитываем метрику precision@k
p_at_k = precision_at_k(model, train, test, K=3)
p_at_k_train = 0
# фиксируем время окончания работы
end_time = time.time()
elapsed_time = end_time - start_time

print(f'Precision@3: {p_at_k:.4f}')
print()
# Вариан 1 - Выбираем случайного пользователя
random_normalized_visitorid = np.random.choice(users)

# Вариант 2 - Вводим оригинальный visitorid
# original_visitorid = 391657
# random_normalized_visitorid = original_visitorid - min_visitorid # приводим его к нормализованному виду

userid = user_to_idx[random_normalized_visitorid]

# получаем рекомендации для пользователя
ids, scores = model.recommend(userid, matrix[userid], N=3, filter_already_liked_items=False)
# преобразуем обратно в оригинальные itemid
original_item_ids = [items[idx] + min_itemid for idx in ids]
# преобразуем обратно в оригинальный visitorid
original_visitorid = random_normalized_visitorid + min_visitorid

# используем pandas для отображения результатов в виде таблицы
rec_user = pd.DataFrame({
    "visitorid": original_visitorid,
    "itemid": original_item_ids,
    "score": scores,
    "already_liked": np.in1d(ids, matrix[userid].indices.ravel())  # преобразуем в одномерный массив
})
print(rec_user)
print()
set1 = set(df[df["visitorid"] == original_visitorid]["itemid"].unique().tolist())
set2 = set(original_item_ids)
print(f'Соответсвие itemid между рекомендациями и фактом {set1&set2}')
print()
print(rec_user["already_liked"].value_counts())
print()

# сохраняем результаты
results_implicit = add_results(results_implicit, "MF_LMF", elapsed_time, p_at_k_train, p_at_k)
display(results_implicit)

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

Precision@3: 0.0042

   visitorid  itemid      score  already_liked
0    1018116   86000  12.749302          False
1    1018116  183313  12.007761          False
2    1018116  374092  11.476935          False

Соответсвие itemid между рекомендациями и фактом set()

already_liked
False    3
Name: count, dtype: int64

,Model,Time,train_Precision@3,test_Precision@3
0,NNM_CosinRecomender,4.854386,0,0.051156
1,NNM_CosinRecomender_Optuna,5.049159,0,0.052387
2,NNM_ItemItemRecomender,4.798687,0,0.071307
3,NNM_ItemItemRecomender_Optuna,5.474812,0,0.072997
4,NNM_BM25Recomender,4.87209,0,0.125621
5,NNM_BM25Recomender_Optuna,8.314192,0,0.131567
6,MF_ALS,21.649938,0,0.084578
7,MF_ALS_Optuna,52.817272,0,0.10329
8,MF_BPR,25.006213,0,0.024703
9,MF_BPR_Optuna,22.199291,0,0.06069
10,MF_LMF,15.123544,0,0.004167

#### Подбор гиперпараметров с помощью **OPTUNA**

In [26]:
def objective(trial):
    # Получаем гиперпараметры из trial
    factors = trial.suggest_int("factors", 50, 200)
    regularization = trial.suggest_loguniform("regularization", 1e-4, 1e-1)
    learning_rate = trial.suggest_uniform("learning_rate", 1e-4, 1e-1)
    neg_prop = trial.suggest_int("factors", 10, 100)
    
    # Формируем и обучаем модель с новыми параметрами
    model = LogisticMatrixFactorization(
        factors=factors,
        regularization=regularization,
        learning_rate=learning_rate,
        neg_prop=neg_prop,
        iterations=20,
        random_state=RANDOM_SEED,
        num_threads=8
    )
    model.fit(train)

    # Оцениваем модель
    p_at_k = precision_at_k(model, train, test, K=3)
    
    return p_at_k

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=10, show_progress_bar=True)

best_params = study.best_trial.params
print("Лучшие параметры:", best_params)

[I 2025-01-17 14:11:08,385] A new study created in memory with name: no-name-ef809515-60d8-42aa-a6cd-3f810ceeb4d2

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:12:17,302] Trial 0 finished with value: 0.00010379442772200887 and parameters: {'factors': 169, 'regularization': 0.0019481205823703668, 'learning_rate': 0.08370948585164208}. Best is trial 0 with value: 0.00010379442772200887.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:13:38,635] Trial 1 finished with value: 5.931110155543364e-05 and parameters: {'factors': 180, 'regularization': 0.0020347276602625444, 'learning_rate': 0.009750596202187531}. Best is trial 0 with value: 0.00010379442772200887.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:15:11,948] Trial 2 finished with value: 8.896665233315046e-05 and parameters: {'factors': 200, 'regularization': 0.0065097050114159205, 'learning_rate': 0.08143349973503292}. Best is trial 0 with value: 0.00010379442772200887.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:15:49,046] Trial 3 finished with value: 7.413887694429205e-05 and parameters: {'factors': 93, 'regularization': 0.09830862216651631, 'learning_rate': 0.08757146582141932}. Best is trial 0 with value: 0.00010379442772200887.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:16:28,469] Trial 4 finished with value: 7.413887694429205e-05 and parameters: {'factors': 98, 'regularization': 0.00030340606560144484, 'learning_rate': 0.05987683342169156}. Best is trial 0 with value: 0.00010379442772200887.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:16:57,875] Trial 5 finished with value: 4.448332616657523e-05 and parameters: {'factors': 68, 'regularization': 0.000838452967815687, 'learning_rate': 0.015173666587539993}. Best is trial 0 with value: 0.00010379442772200887.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:17:24,612] Trial 6 finished with value: 0.0001482777538885841 and parameters: {'factors': 62, 'regularization': 0.028841349395300156, 'learning_rate': 0.09847818260905158}. Best is trial 6 with value: 0.0001482777538885841.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:18:12,488] Trial 7 finished with value: 0.00011862220311086728 and parameters: {'factors': 120, 'regularization': 0.09800740636869071, 'learning_rate': 0.07452891217291785}. Best is trial 6 with value: 0.0001482777538885841.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:19:09,633] Trial 8 finished with value: 0.00010379442772200887 and parameters: {'factors': 137, 'regularization': 0.03488181697206647, 'learning_rate': 0.0256997033163558}. Best is trial 6 with value: 0.0001482777538885841.

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:19:46,224] Trial 9 finished with value: 8.896665233315046e-05 and parameters: {'factors': 94, 'regularization': 0.058418027877601884, 'learning_rate': 0.04075649494665504}. Best is trial 6 with value: 0.0001482777538885841.
Лучшие параметры: {'factors': 62, 'regularization': 0.028841349395300156, 'learning_rate': 0.09847818260905158}

In [27]:
# визуализация среза
optuna.visualization.plot_slice(study, target_name="p_at_k")

In [28]:
# фиксируем время начала работы
start_time = time.time()
# формируем параметры модели и обучаем её
model = LogisticMatrixFactorization(**best_params, 
                                    neg_prop=30, 
                                    iterations=100, 
                                    random_state=RANDOM_SEED, 
                                    num_threads=8)

model.fit(train)

# расчитываем метрику precision@k
p_at_k = precision_at_k(model, train, test, K=3)
p_at_k_train = 0
# фиксируем время окончания работы
end_time = time.time()
elapsed_time = end_time - start_time

print(f'Precision@3: {p_at_k:.4f}')
print()
# Вариан 1 - Выбираем случайного пользователя
random_normalized_visitorid = np.random.choice(users)

# Вариант 2 - Вводим оригинальный visitorid
# original_visitorid = 391657
# random_normalized_visitorid = original_visitorid - min_visitorid # приводим его к нормализованному виду

userid = user_to_idx[random_normalized_visitorid]

# получаем рекомендации для пользователя
ids, scores = model.recommend(userid, matrix[userid], N=3, filter_already_liked_items=False)
# преобразуем обратно в оригинальные itemid
original_item_ids = [items[idx] + min_itemid for idx in ids]
# преобразуем обратно в оригинальный visitorid
original_visitorid = random_normalized_visitorid + min_visitorid

# используем pandas для отображения результатов в виде таблицы
rec_user = pd.DataFrame({
    "visitorid": original_visitorid,
    "itemid": original_item_ids,
    "score": scores,
    "already_liked": np.in1d(ids, matrix[userid].indices.ravel())  # преобразуем в одномерный массив
})
print(rec_user)
print()
set1 = set(df[df["visitorid"] == original_visitorid]["itemid"].unique().tolist())
set2 = set(original_item_ids)
print(f'Соответсвие itemid между рекомендациями и фактом {set1&set2}')
print()
print(rec_user["already_liked"].value_counts())
print()

# сохраняем результаты
results_implicit = add_results(results_implicit, "MF_LMF_Optuna", elapsed_time, p_at_k_train, p_at_k)
display(results_implicit)

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

Precision@3: 0.0004

   visitorid  itemid      score  already_liked
0      52519  140472  11.446856          False
1      52519  218531  11.021364          False
2      52519  193488  10.887375          False

Соответсвие itemid между рекомендациями и фактом set()

already_liked
False    3
Name: count, dtype: int64

,Model,Time,train_Precision@3,test_Precision@3
0,NNM_CosinRecomender,4.854386,0,0.051156
1,NNM_CosinRecomender_Optuna,5.049159,0,0.052387
2,NNM_ItemItemRecomender,4.798687,0,0.071307
3,NNM_ItemItemRecomender_Optuna,5.474812,0,0.072997
4,NNM_BM25Recomender,4.87209,0,0.125621
5,NNM_BM25Recomender_Optuna,8.314192,0,0.131567
6,MF_ALS,21.649938,0,0.084578
7,MF_ALS_Optuna,52.817272,0,0.10329
8,MF_BPR,25.006213,0,0.024703
9,MF_BPR_Optuna,22.199291,0,0.06069
10,MF_LMF,15.123544,0,0.004167
11,MF_LMF_Optuna,45.255306,0,0.000371

### 4. Модель `NMSLibModel` - <span style="color:red"> с данной надстройкой и библиотекой nmslib до конца не разобралcя

**Модель `NMSLibModel`** из библиотеки Implicit представляет собой оболочку для использования библиотеки Non-Metric Space Library (NMSLIB) внутри Implicit. NMSLIB — это библиотека для эффективного поиска ближайшего соседа в метрических и неметрических пространствах. Модель `NMSLibModel` позволяет использовать мощные алгоритмы NMSLIB для рекомендательных систем.

#### Основные особенности модели `NMSLibModel`:

1. **Эффективный поиск ближайшего соседа**: NMSLIB предоставляет высокоэффективные алгоритмы для поиска ближайших соседей даже в больших наборах данных. Это особенно полезно для задач, связанных с коллаборативной фильтрацией, где требуется находить похожие элементы или пользователей.

2. **Поддержка различных метрик**: NMSLIB поддерживает множество различных метрик расстояния, включая евклидово расстояние, косинусное сходство, манхэттенское расстояние и многие другие. Это позволяет выбирать подходящую метрику в зависимости от специфики задачи.

3. **Параллельная обработка**: NMSLIB поддерживает параллельную обработку данных, что ускоряет работу с большими объемами информации.

4. **Простота интеграции**: Модель `NMSLibModel` легко интегрируется с библиотекой Implicit, позволяя использовать преимущества NMSLIB без необходимости глубокого погружения в детали этой библиотеки.

#### Пример использования `NMSLibModel`:

```python
from implicit.nearest_neighbours import NMSLibModel

# Создание модели
model = NMSLibModel(method='hnsw', space='cosinesimil', index_params={'M': 16, 'post': 0}, query_time_params={})

# Обучение модели
model.fit(train)

# Получение рекомендаций
user_id = 123
n_recommendations = 10
recommendations = model.recommend(user_id, n_recommendations)
```

#### Ключевые параметры `NMSLibModel`:

1. **method**: Метод индексирования, поддерживаемый NMSLIB. Возможные значения включают `hnsw`, `sw-graph`, `vp-tree` и другие.

2. **space**: Пространство, в котором выполняется поиск. Поддерживаются различные метрики, такие как `l2` (евклидово расстояние), `cosinesimil` (косинусное сходство) и другие.

3. **index_params**: Параметры индексации, зависящие от выбранного метода. Например, для метода `hnsw` параметр `M` определяет количество соседей для каждого элемента.

4. **query_time_params**: Параметры времени запроса, влияющие на точность и скорость поиска.

#### Заключение

Модель `NMSLibModel` предоставляет мощный инструмент для поиска ближайших соседей в рамках рекомендательных систем. Благодаря поддержке различных метрик и высокопроизводительных алгоритмов, она может существенно улучшить качество рекомендаций, особенно в условиях больших объемов данных.

In [29]:
# фиксируем время начала работы
start_time = time.time()
# формируем параметры модели и обучаем её - параметры подобраны в модели ALS в одном из прошлых этапов
model = NMSLibModel(model=AlternatingLeastSquares(factors=92, 
                                                    regularization=0.0003856975837335963, 
                                                    alpha=7.437140417776456, 
                                                    use_native=True, 
                                                    use_cg=True, 
                                                    calculate_training_loss=False,
                                                    random_state=RANDOM_SEED,
                                                    iterations=30,
                                                    num_threads=8),
                    method="hnsw",              # метод индексирования, используемый для поиска ближайших соседей. HNSW (Hierarchical Navigable Small World Graphs) является эффективным методом для поиска KNN (k-ближайших соседей) в больших наборах данных.
                    space="lp_sparse",          # пространство метрик, которое используется для измерения расстояния между точками. В данном случае выбрано (Манхэттенское расстояние), подходящее для разреженных данных.
                    index_params={
                        'M': 7,                 # параметр контролирует количество соединений на каждом уровне графа HNSW. Большее значение M увеличивает точность поиска, но также увеличивает затраты памяти и времени на построение индекса.
                        'efConstruction': 200,  # параметр управляет качеством построения индекса. Более высокие значения могут улучшить качество индексации, но увеличивают время построения.
                        'indexThreadQty': 8,    # количество потоков, используемых для построения индекса
                        'post': 1,              # определяет количество кандидатов для финального этапа поиска после того, как HNSW находит начальные точки. Большие значения могут увеличить точность, но замедляют поиск.
                    },
                    query_time_params={},
                    )
# обучение модели
model.fit(train)

# расчитываем метрику precision@k
p_at_k = precision_at_k(model, train, test, K=3)
p_at_k_train = 0
# фиксируем время окончания работы
end_time = time.time()
elapsed_time = end_time - start_time

print(f'Precision@3: {p_at_k:.4f}')
print()

# Вариан 1 - Выбираем случайного пользователя
random_normalized_visitorid = np.random.choice(users)

# Вариант 2 - Вводим оригинальный visitorid
# original_visitorid = 391657
# random_normalized_visitorid = original_visitorid - min_visitorid # приводим его к нормализованному виду

userid = user_to_idx[random_normalized_visitorid]

# получаем рекомендации для пользователя
ids, scores = model.recommend(userid, matrix[userid], N=3, filter_already_liked_items=False)
# преобразуем обратно в оригинальные itemid
original_item_ids = [items[idx] + min_itemid for idx in ids]
# преобразуем обратно в оригинальный visitorid
original_visitorid = random_normalized_visitorid + min_visitorid

# используем pandas для отображения результатов в виде таблицы
rec_user = pd.DataFrame({
    "visitorid": original_visitorid,
    "itemid": original_item_ids,
    "score": scores,
    "already_liked": np.in1d(ids, matrix[userid].indices.ravel())  # преобразуем в одномерный массив
})
print(rec_user)
print()
set1 = set(df[df["visitorid"] == original_visitorid]["itemid"].unique().tolist())
set2 = set(original_item_ids)
print(f'Соответсвие itemid между рекомендациями и фактом {set1&set2}')
print()
print(rec_user["already_liked"].value_counts())
print()

# сохраняем результаты
results_implicit = add_results(results_implicit, "NMSLibModel", elapsed_time, p_at_k_train, p_at_k)
display(results_implicit)

  0%|          | 0/30 [00:00<?, ?it/s]

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

  0%|          | 0/38759 [00:00<?, ?it/s]

Precision@3: 0.0829

   visitorid  itemid     score  already_liked
0     885078  455183  0.886162          False
1     885078  234255  0.858164          False
2     885078  328696  0.849749          False

Соответсвие itemid между рекомендациями и фактом set()

already_liked
False    3
Name: count, dtype: int64

,Model,Time,train_Precision@3,test_Precision@3
0,NNM_CosinRecomender,4.854386,0,0.051156
1,NNM_CosinRecomender_Optuna,5.049159,0,0.052387
2,NNM_ItemItemRecomender,4.798687,0,0.071307
3,NNM_ItemItemRecomender_Optuna,5.474812,0,0.072997
4,NNM_BM25Recomender,4.87209,0,0.125621
5,NNM_BM25Recomender_Optuna,8.314192,0,0.131567
6,MF_ALS,21.649938,0,0.084578
7,MF_ALS_Optuna,52.817272,0,0.10329
8,MF_BPR,25.006213,0,0.024703
9,MF_BPR_Optuna,22.199291,0,0.06069
10,MF_LMF,15.123544,0,0.004167
11,MF_LMF_Optuna,45.255306,0,0.000371
12,NMSLibModel,62.61669,0,0.082902

#### Подбор гиперпараметров с помощью **OPTUNA**

In [30]:

def objective(trial):
    # Получение гиперпараметров из trial
    # factors = trial.suggest_int("factors", 10, 150)
    # regularization = trial.suggest_loguniform("regularization", 1e-6, 1e-1)
    # M = trial.suggest_int("M", 1, 20)
    # ef_construction = trial.suggest_int("efConstruction", 50, 500)
    # index_thread_qty = trial.suggest_int("indexThreadQty", 1, 10)
    # post = trial.suggest_int("post", 1, 20)
    method = trial.suggest_categorical("method", ["hnsw", # hnsw a Hierarchical Navigable Small World Graph.
                                                  #"sw-graph", # sw-graph a Small World Graph.
                                                  #"vptree", # vptree a Vantage-Point tree with a pruning rule adaptable to non-metric distances
                                                  #"napp", # vptree a Vantage-Point tree with a pruning rule adaptable to non-metric distances
                                                  #"simple_invindx", # simple_invindx a vanilla, uncompressed, inverted index, which has no parameters
                                                  #"brute_force"]) # brute_force a brute-force search, which has no parameters
                                                ])
    
    space = trial.suggest_categorical("space", ["lp", 
                                                "l1", 
                                                "l2", 
                                                "linf", 
                                                "l2sqrt_sift", 
                                                "lp_sparse", 
                                                "l1_sparse", 
                                                "l2_sparse", 
                                                "linf_sparse",
                                                "cosinesimil",
                                                "negdotprod",
                                                "angulardist",
                                                "cosinesimil_sparse",
                                                "cosinesimil_sparse_fast"
                                                "negdotprod_sparse",
                                                "negdotprod_sparse_fast",
                                                "angulardist_sparse",
                                                "angulardist_sparse_fast"
                                                "kldivfast",
                                                "kldivfastrq",
                                                "kldivgenslow",
                                                "kldivgenfast",
                                                "kldivgenfastrq",
                                                "itakurasaitoslow",
                                                "itakurasaitofast",
                                                "itakurasaitofastrq",
                                                "jsdivslow",
                                                "jsdivfast",
                                                "jsdivfastapprox",
                                                "jsmetrslow",
                                                "jsmetrfast",
                                                "jsmetrfastapprox",
                                                "renyidiv_slow",
                                                "renyidiv_fast",
                                                "leven",
                                                "normleven",
                                                "jaccard_sparse",
                                                "bit_jaccard",
                                                "bit_hamming",
                                                ])
    
    # Создание и обучение модели с новыми параметрами
    als_model = AlternatingLeastSquares(factors=92, 
                                        regularization=0.0003856975837335963, 
                                        alpha=7.437140417776456, 
                                        use_native=True, 
                                        use_cg=True, 
                                        calculate_training_loss=False,
                                        random_state=RANDOM_SEED,
                                        iterations=1,
                                        num_threads=8)
    als_model.fit(train)
    
    model = NMSLibModel(
        model=als_model,
        method=method,
        space=space,
        index_params={
            'M': 7,
            'efConstruction': 200,
            'indexThreadQty': 8,
            'post': 1,
        },
        query_time_params={}
    )
    model.fit(train)
    
    # Оцениваем модель
    p_at_k = precision_at_k(model, train, test, K=3)
    
    return p_at_k

# Создаем исследование Optuna
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=10, show_progress_bar=True)

# Выводим лучшие параметры
best_params = study.best_trial.params
print("Лучшие параметры:", best_params)

[I 2025-01-17 14:27:36,274] A new study created in memory with name: no-name-e5a25b82-0b6c-47ee-a914-d21a096b6ffa

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
**

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:28:08,696] Trial 0 finished with value: 0.0210702688275678 and parameters: {'method': 'hnsw', 'space': 'leven'}. Best is trial 0 with value: 0.0210702688275678.

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:28:45,515] Trial 1 finished with value: 0.019869219021070268 and parameters: {'method': 'hnsw', 'space': 'cosinesimil_sparse'}. Best is trial 0 with value: 0.0210702688275678.

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
****************************************************


0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:29:19,860] Trial 2 finished with value: 0.020284396731958303 and parameters: {'method': 'hnsw', 'space': 'cosinesimil_sparse'}. Best is trial 0 with value: 0.0210702688275678.

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
****************************************************


0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
****************************************************

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:29:53,942] Trial 3 finished with value: 0.019720941267181685 and parameters: {'method': 'hnsw', 'space': 'jsdivfastapprox'}. Best is trial 0 with value: 0.0210702688275678.

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:30:28,946] Trial 4 finished with value: 0.019557835737904244 and parameters: {'method': 'hnsw', 'space': 'jsmetrslow'}. Best is trial 0 with value: 0.0210702688275678.

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
****************************************************


0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:31:03,358] Trial 5 finished with value: 0.020714402218235197 and parameters: {'method': 'hnsw', 'space': 'jsdivfast'}. Best is trial 0 with value: 0.0210702688275678.

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
*

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
****************************************************

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:31:38,456] Trial 6 finished with value: 0.019824735694903693 and parameters: {'method': 'hnsw', 'space': 'cosinesimil'}. Best is trial 0 with value: 0.0210702688275678.

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
****************************************************

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:32:13,004] Trial 7 finished with value: 0.020195430079625154 and parameters: {'method': 'hnsw', 'space': 'kldivgenslow'}. Best is trial 0 with value: 0.0210702688275678.

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
****************************************************
*

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
*

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:32:48,797] Trial 8 finished with value: 0.020210257855014013 and parameters: {'method': 'hnsw', 'space': 'l2sqrt_sift'}. Best is trial 0 with value: 0.0210702688275678.

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
****************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:33:23,945] Trial 9 finished with value: 0.019231624679349357 and parameters: {'method': 'hnsw', 'space': 'kldivgenfastrq'}. Best is trial 0 with value: 0.0210702688275678.
Лучшие параметры: {'method': 'hnsw', 'space': 'leven'}

In [31]:
# фиксируем время начала работы
start_time = time.time()
# формируем параметры модели и обучаем её
model = NMSLibModel(model=AlternatingLeastSquares(factors=92, 
                                                    regularization=0.0003856975837335963, 
                                                    alpha=7.437140417776456, 
                                                    use_native=True, 
                                                    use_cg=True, 
                                                    calculate_training_loss=False,
                                                    random_state=RANDOM_SEED,
                                                    iterations=30,
                                                    num_threads=8),
                    method="hnsw", # метод индексирования, используемый для поиска ближайших соседей. HNSW (Hierarchical Navigable Small World Graphs) является эффективным методом для поиска KNN (k-ближайших соседей) в больших наборах данных.
                    space="leven",
                    index_params={
                        'M': 7, # параметр контролирует количество соединений на каждом уровне графа HNSW. Большее значение M увеличивает точность поиска, но также увеличивает затраты памяти и времени на построение индекса.
                        'efConstruction': 200, # параметр управляет качеством построения индекса. Более высокие значения могут улучшить качество индексации, но увеличивают время построения.
                        'indexThreadQty': 8, # количество потоков, используемых для построения индекса
                        'post': 1, # определяет количество кандидатов для финального этапа поиска после того, как HNSW находит начальные точки. Большие значения могут увеличить точность, но замедляют поиск.
                    },
                    query_time_params={},
                    )
# обучение модели
model.fit(train)

# расчитываем метрику precision@k
p_at_k = precision_at_k(model, train, test, K=3)
p_at_k_train = 0
# фиксируем время окончания работы
end_time = time.time()
elapsed_time = end_time - start_time

print(f'Precision@3: {p_at_k:.4f}')
print()

# Вариан 1 - Выбираем случайного пользователя
random_normalized_visitorid = np.random.choice(users)

# Вариант 2 - Вводим оригинальный visitorid
# original_visitorid = 391657
# random_normalized_visitorid = original_visitorid - min_visitorid # приводим его к нормализованному виду

userid = user_to_idx[random_normalized_visitorid]

# получаем рекомендации для пользователя
ids, scores = model.recommend(userid, matrix[userid], N=3, filter_already_liked_items=False)
# преобразуем обратно в оригинальные itemid
original_item_ids = [items[idx] + min_itemid for idx in ids]
# преобразуем обратно в оригинальный visitorid
original_visitorid = random_normalized_visitorid + min_visitorid

# используем pandas для отображения результатов в виде таблицы
rec_user = pd.DataFrame({
    "visitorid": original_visitorid,
    "itemid": original_item_ids,
    "score": scores,
    "already_liked": np.in1d(ids, matrix[userid].indices.ravel())  # преобразуем в одномерный массив
})
print(rec_user)
print()
set1 = set(df[df["visitorid"] == original_visitorid]["itemid"].unique().tolist())
set2 = set(original_item_ids)
print(f'Соответсвие itemid между рекомендациями и фактом {set1&set2}')
print()
print(rec_user["already_liked"].value_counts())
print()

# сохраняем результаты
results_implicit = add_results(results_implicit, "NMSLibModel_Optuna", elapsed_time, p_at_k_train, p_at_k)
display(results_implicit)

  0%|          | 0/30 [00:00<?, ?it/s]

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
****************************************************


0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

  0%|          | 0/38759 [00:00<?, ?it/s]

Precision@3: 0.0830

   visitorid  itemid     score  already_liked
0    1167617  227161  0.781334           True
1    1167617   12765  0.749341          False
2    1167617  255725  0.731619          False

Соответсвие itemid между рекомендациями и фактом {227161}

already_liked
False    2
True     1
Name: count, dtype: int64

,Model,Time,train_Precision@3,test_Precision@3
0,NNM_CosinRecomender,4.854386,0,0.051156
1,NNM_CosinRecomender_Optuna,5.049159,0,0.052387
2,NNM_ItemItemRecomender,4.798687,0,0.071307
3,NNM_ItemItemRecomender_Optuna,5.474812,0,0.072997
4,NNM_BM25Recomender,4.87209,0,0.125621
5,NNM_BM25Recomender_Optuna,8.314192,0,0.131567
6,MF_ALS,21.649938,0,0.084578
7,MF_ALS_Optuna,52.817272,0,0.10329
8,MF_BPR,25.006213,0,0.024703
9,MF_BPR_Optuna,22.199291,0,0.06069
10,MF_LMF,15.123544,0,0.004167
11,MF_LMF_Optuna,45.255306,0,0.000371
12,NMSLibModel,62.61669,0,0.082902
13,NMSLibModel_Optuna,62.470012,0,0.082976

### 5. Лучшая модель по результатам оценки

In [32]:
# выводим результаты
display(results_implicit.sort_values(by="test_Precision@3", ascending=False))

,Model,Time,train_Precision@3,test_Precision@3
5,NNM_BM25Recomender_Optuna,8.314192,0,0.131567
4,NNM_BM25Recomender,4.87209,0,0.125621
7,MF_ALS_Optuna,52.817272,0,0.10329
6,MF_ALS,21.649938,0,0.084578
13,NMSLibModel_Optuna,62.470012,0,0.082976
12,NMSLibModel,62.61669,0,0.082902
3,NNM_ItemItemRecomender_Optuna,5.474812,0,0.072997
2,NNM_ItemItemRecomender,4.798687,0,0.071307
9,MF_BPR_Optuna,22.199291,0,0.06069
1,NNM_CosinRecomender_Optuna,5.049159,0,0.052387
0,NNM_CosinRecomender,4.854386,0,0.051156
8,MF_BPR,25.006213,0,0.024703
10,MF_LMF,15.123544,0,0.004167
11,MF_LMF_Optuna,45.255306,0,0.000371

**<span style="color:green"> Лучшая модель NNM_BM25Recommender. Проведем настройку интервалов гиперпараметров по результатам прошлого подбора и еще раз подбор пораметров с помощью OPTUNA.**

In [33]:
%%time
def objective(trial):
    # Получаем гиперпараметры из trial
    K = trial.suggest_int('K', 300, 700)
    K1 = trial.suggest_float('K1', low=0.01, high=0.5, step=0.005)
    B = trial.suggest_float('B', low=0.01, high=0.15, step=0.001)
    
    # Обучаем модель с новыми параметрами
    model = BM25Recommender(
        K=K,
        K1=K1,
        B=B,
        num_threads=8
    )
    
    model.fit(train)

    # Оцениваем модель
    p_at_k = precision_at_k(model, train, test, K=3)
    
    return p_at_k

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100, show_progress_bar=True)

best_params = study.best_trial.params
print("Лучшие параметры:", best_params)

[I 2025-01-17 14:35:15,297] A new study created in memory with name: no-name-2ff7fddb-6dde-45c4-a0ca-18a75ed493a1

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:35:26,391] Trial 0 finished with value: 0.130588217849676 and parameters: {'K': 666, 'K1': 0.5, 'B': 0.059000000000000004}. Best is trial 0 with value: 0.130588217849676.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:35:34,164] Trial 1 finished with value: 0.1309885677851752 and parameters: {'K': 376, 'K1': 0.105, 'B': 0.137}. Best is trial 1 with value: 0.1309885677851752.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:35:44,570] Trial 2 finished with value: 0.1308847733574532 and parameters: {'K': 673, 'K1': 0.165, 'B': 0.088}. Best is trial 1 with value: 0.1309885677851752.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:35:52,335] Trial 3 finished with value: 0.13069201227739802 and parameters: {'K': 352, 'K1': 0.48500000000000004, 'B': 0.13}. Best is trial 1 with value: 0.1309885677851752.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:36:00,554] Trial 4 finished with value: 0.13060304562506486 and parameters: {'K': 392, 'K1': 0.5, 'B': 0.08499999999999999}. Best is trial 1 with value: 0.1309885677851752.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:36:08,802] Trial 5 finished with value: 0.13048442342195402 and parameters: {'K': 411, 'K1': 0.37, 'B': 0.072}. Best is trial 1 with value: 0.1309885677851752.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:36:16,760] Trial 6 finished with value: 0.1306623567266203 and parameters: {'K': 325, 'K1': 0.14500000000000002, 'B': 0.049}. Best is trial 1 with value: 0.1309885677851752.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:36:26,583] Trial 7 finished with value: 0.13086994558206433 and parameters: {'K': 619, 'K1': 0.305, 'B': 0.14200000000000002}. Best is trial 1 with value: 0.1309885677851752.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:36:35,108] Trial 8 finished with value: 0.13036580121884314 and parameters: {'K': 455, 'K1': 0.27, 'B': 0.075}. Best is trial 1 with value: 0.1309885677851752.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:36:43,267] Trial 9 finished with value: 0.13103305111134175 and parameters: {'K': 387, 'K1': 0.09999999999999999, 'B': 0.14500000000000002}. Best is trial 9 with value: 0.13103305111134175.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:36:52,600] Trial 10 finished with value: 0.13069201227739802 and parameters: {'K': 536, 'K1': 0.035, 'B': 0.012}. Best is trial 9 with value: 0.13103305111134175.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:37:01,474] Trial 11 finished with value: 0.13014338458801025 and parameters: {'K': 501, 'K1': 0.01, 'B': 0.11699999999999999}. Best is trial 9 with value: 0.13103305111134175.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:37:09,084] Trial 12 finished with value: 0.13107753443750833 and parameters: {'K': 301, 'K1': 0.135, 'B': 0.11}. Best is trial 12 with value: 0.13107753443750833.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:37:17,013] Trial 13 finished with value: 0.13063270117584258 and parameters: {'K': 307, 'K1': 0.21000000000000002, 'B': 0.109}. Best is trial 12 with value: 0.13107753443750833.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:37:26,591] Trial 14 finished with value: 0.13113684553906377 and parameters: {'K': 441, 'K1': 0.09999999999999999, 'B': 0.15}. Best is trial 14 with value: 0.13113684553906377.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:37:37,348] Trial 15 finished with value: 0.13097374000978634 and parameters: {'K': 583, 'K1': 0.06999999999999999, 'B': 0.106}. Best is trial 14 with value: 0.13113684553906377.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:37:47,101] Trial 16 finished with value: 0.13057339007428714 and parameters: {'K': 463, 'K1': 0.21000000000000002, 'B': 0.12}. Best is trial 14 with value: 0.13113684553906377.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:37:56,258] Trial 17 finished with value: 0.13103305111134175 and parameters: {'K': 433, 'K1': 0.155, 'B': 0.09799999999999999}. Best is trial 14 with value: 0.13113684553906377.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:38:06,305] Trial 18 finished with value: 0.13100339556056406 and parameters: {'K': 524, 'K1': 0.32, 'B': 0.123}. Best is trial 14 with value: 0.13113684553906377.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:38:14,420] Trial 19 finished with value: 0.13121098441600806 and parameters: {'K': 341, 'K1': 0.06999999999999999, 'B': 0.14900000000000002}. Best is trial 19 with value: 0.13121098441600806.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:38:22,820] Trial 20 finished with value: 0.13121098441600806 and parameters: {'K': 347, 'K1': 0.06999999999999999, 'B': 0.14900000000000002}. Best is trial 19 with value: 0.13121098441600806.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:38:31,875] Trial 21 finished with value: 0.13097374000978634 and parameters: {'K': 429, 'K1': 0.060000000000000005, 'B': 0.15}. Best is trial 19 with value: 0.13121098441600806.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:38:40,134] Trial 22 finished with value: 0.13106270666211947 and parameters: {'K': 343, 'K1': 0.08499999999999999, 'B': 0.132}. Best is trial 19 with value: 0.13121098441600806.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:38:48,469] Trial 23 finished with value: 0.13029166234189885 and parameters: {'K': 355, 'K1': 0.01, 'B': 0.14900000000000002}. Best is trial 19 with value: 0.13121098441600806.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:38:58,588] Trial 24 finished with value: 0.130588217849676 and parameters: {'K': 479, 'K1': 0.21500000000000002, 'B': 0.132}. Best is trial 19 with value: 0.13121098441600806.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:39:07,412] Trial 25 finished with value: 0.130588217849676 and parameters: {'K': 369, 'K1': 0.11, 'B': 0.033}. Best is trial 19 with value: 0.13121098441600806.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:39:16,650] Trial 26 finished with value: 0.13115167331445263 and parameters: {'K': 420, 'K1': 0.05, 'B': 0.15}. Best is trial 19 with value: 0.13121098441600806.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:39:25,669] Trial 27 finished with value: 0.13121098441600806 and parameters: {'K': 408, 'K1': 0.05, 'B': 0.126}. Best is trial 19 with value: 0.13121098441600806.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:39:33,903] Trial 28 finished with value: 0.13092925668361977 and parameters: {'K': 324, 'K1': 0.18500000000000003, 'B': 0.126}. Best is trial 19 with value: 0.13121098441600806.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:39:42,873] Trial 29 finished with value: 0.13075132337895345 and parameters: {'K': 403, 'K1': 0.44, 'B': 0.097}. Best is trial 19 with value: 0.13121098441600806.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:39:51,184] Trial 30 finished with value: 0.13069201227739802 and parameters: {'K': 335, 'K1': 0.03, 'B': 0.138}. Best is trial 19 with value: 0.13121098441600806.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:40:00,052] Trial 31 finished with value: 0.1312702955175635 and parameters: {'K': 406, 'K1': 0.05, 'B': 0.14}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:40:08,664] Trial 32 finished with value: 0.13106270666211947 and parameters: {'K': 377, 'K1': 0.125, 'B': 0.139}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:40:17,283] Trial 33 finished with value: 0.1310478788867306 and parameters: {'K': 367, 'K1': 0.065, 'B': 0.137}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:40:26,374] Trial 34 finished with value: 0.13097374000978634 and parameters: {'K': 399, 'K1': 0.04, 'B': 0.11499999999999999}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:40:35,040] Trial 35 finished with value: 0.13089960113284205 and parameters: {'K': 344, 'K1': 0.17500000000000002, 'B': 0.129}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:40:44,956] Trial 36 finished with value: 0.13095891223439748 and parameters: {'K': 486, 'K1': 0.08, 'B': 0.139}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:40:56,799] Trial 37 finished with value: 0.130588217849676 and parameters: {'K': 696, 'K1': 0.12, 'B': 0.057}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:41:04,938] Trial 38 finished with value: 0.1302323512403434 and parameters: {'K': 322, 'K1': 0.01, 'B': 0.134}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:41:13,538] Trial 39 finished with value: 0.13086994558206433 and parameters: {'K': 362, 'K1': 0.385, 'B': 0.125}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:41:22,634] Trial 40 finished with value: 0.13118132886523035 and parameters: {'K': 387, 'K1': 0.095, 'B': 0.14200000000000002}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:41:31,611] Trial 41 finished with value: 0.13107753443750833 and parameters: {'K': 388, 'K1': 0.075, 'B': 0.14100000000000001}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:41:40,637] Trial 42 finished with value: 0.1310478788867306 and parameters: {'K': 408, 'K1': 0.04, 'B': 0.14400000000000002}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:41:50,255] Trial 43 finished with value: 0.13115167331445263 and parameters: {'K': 446, 'K1': 0.095, 'B': 0.14400000000000002}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:41:59,015] Trial 44 finished with value: 0.1310182233359529 and parameters: {'K': 376, 'K1': 0.15000000000000002, 'B': 0.13}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:42:08,318] Trial 45 finished with value: 0.13064752895123144 and parameters: {'K': 413, 'K1': 0.03, 'B': 0.119}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:42:16,245] Trial 46 finished with value: 0.13095891223439748 and parameters: {'K': 312, 'K1': 0.255, 'B': 0.14400000000000002}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:42:24,600] Trial 47 finished with value: 0.13086994558206433 and parameters: {'K': 351, 'K1': 0.13, 'B': 0.102}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:42:35,410] Trial 48 finished with value: 0.1311961566406192 and parameters: {'K': 624, 'K1': 0.055, 'B': 0.114}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:42:45,431] Trial 49 finished with value: 0.13113684553906377 and parameters: {'K': 573, 'K1': 0.060000000000000005, 'B': 0.08499999999999999}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:42:55,583] Trial 50 finished with value: 0.13061787340045372 and parameters: {'K': 608, 'K1': 0.03, 'B': 0.093}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:43:04,013] Trial 51 finished with value: 0.13097374000978634 and parameters: {'K': 388, 'K1': 0.095, 'B': 0.11499999999999999}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:43:13,734] Trial 52 finished with value: 0.13113684553906377 and parameters: {'K': 514, 'K1': 0.05, 'B': 0.134}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:43:24,762] Trial 53 finished with value: 0.13097374000978634 and parameters: {'K': 674, 'K1': 0.08, 'B': 0.124}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:43:35,450] Trial 54 finished with value: 0.13086994558206433 and parameters: {'K': 637, 'K1': 0.11, 'B': 0.06999999999999999}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:43:45,117] Trial 55 finished with value: 0.13122581219139692 and parameters: {'K': 560, 'K1': 0.060000000000000005, 'B': 0.11}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:43:54,839] Trial 56 finished with value: 0.13041028454500972 and parameters: {'K': 546, 'K1': 0.02, 'B': 0.113}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:44:05,286] Trial 57 finished with value: 0.13125546774217464 and parameters: {'K': 564, 'K1': 0.055, 'B': 0.127}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:44:15,785] Trial 58 finished with value: 0.13094408445900863 and parameters: {'K': 546, 'K1': 0.06999999999999999, 'B': 0.107}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:44:26,764] Trial 59 finished with value: 0.13113684553906377 and parameters: {'K': 571, 'K1': 0.135, 'B': 0.121}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:44:37,604] Trial 60 finished with value: 0.1309144289082309 and parameters: {'K': 594, 'K1': 0.31, 'B': 0.128}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:44:48,175] Trial 61 finished with value: 0.13113684553906377 and parameters: {'K': 638, 'K1': 0.055, 'B': 0.103}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:44:58,558] Trial 62 finished with value: 0.1311665010898415 and parameters: {'K': 559, 'K1': 0.045000000000000005, 'B': 0.135}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:45:08,208] Trial 63 finished with value: 0.13033614566806542 and parameters: {'K': 465, 'K1': 0.02, 'B': 0.14700000000000002}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:45:18,507] Trial 64 finished with value: 0.13046959564656516 and parameters: {'K': 510, 'K1': 0.11, 'B': 0.014}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:45:30,020] Trial 65 finished with value: 0.13100339556056406 and parameters: {'K': 610, 'K1': 0.08499999999999999, 'B': 0.111}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:45:41,137] Trial 66 finished with value: 0.1311665010898415 and parameters: {'K': 632, 'K1': 0.060000000000000005, 'B': 0.119}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:45:51,888] Trial 67 finished with value: 0.13110718998828605 and parameters: {'K': 650, 'K1': 0.045000000000000005, 'B': 0.128}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:46:01,624] Trial 68 finished with value: 0.130588217849676 and parameters: {'K': 527, 'K1': 0.195, 'B': 0.14600000000000002}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:46:11,399] Trial 69 finished with value: 0.1308847733574532 and parameters: {'K': 492, 'K1': 0.16, 'B': 0.137}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:46:20,475] Trial 70 finished with value: 0.1304547678711763 and parameters: {'K': 314, 'K1': 0.015, 'B': 0.15}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:46:34,050] Trial 71 finished with value: 0.1311220177636749 and parameters: {'K': 593, 'K1': 0.09, 'B': 0.14200000000000002}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:46:46,105] Trial 72 finished with value: 0.1309885677851752 and parameters: {'K': 426, 'K1': 0.065, 'B': 0.132}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:46:57,456] Trial 73 finished with value: 0.1310478788867306 and parameters: {'K': 332, 'K1': 0.11, 'B': 0.14}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:47:07,904] Trial 74 finished with value: 0.1309885677851752 and parameters: {'K': 379, 'K1': 0.075, 'B': 0.124}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:47:17,606] Trial 75 finished with value: 0.13067718450200916 and parameters: {'K': 342, 'K1': 0.03, 'B': 0.14700000000000002}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:47:27,475] Trial 76 finished with value: 0.13113684553906377 and parameters: {'K': 361, 'K1': 0.095, 'B': 0.136}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:47:37,469] Trial 77 finished with value: 0.13075132337895345 and parameters: {'K': 398, 'K1': 0.34500000000000003, 'B': 0.14200000000000002}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:47:47,583] Trial 78 finished with value: 0.13079580670512003 and parameters: {'K': 458, 'K1': 0.24500000000000002, 'B': 0.131}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:47:57,686] Trial 79 finished with value: 0.13064752895123144 and parameters: {'K': 474, 'K1': 0.04, 'B': 0.08}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:48:07,358] Trial 80 finished with value: 0.13094408445900863 and parameters: {'K': 445, 'K1': 0.12, 'B': 0.122}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:48:17,992] Trial 81 finished with value: 0.13125546774217464 and parameters: {'K': 555, 'K1': 0.055, 'B': 0.134}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:48:28,455] Trial 82 finished with value: 0.13121098441600806 and parameters: {'K': 564, 'K1': 0.055, 'B': 0.11699999999999999}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:48:38,755] Trial 83 finished with value: 0.13121098441600806 and parameters: {'K': 553, 'K1': 0.055, 'B': 0.114}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:48:49,039] Trial 84 finished with value: 0.1309885677851752 and parameters: {'K': 552, 'K1': 0.06999999999999999, 'B': 0.11699999999999999}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:48:59,669] Trial 85 finished with value: 0.13051407897273173 and parameters: {'K': 565, 'K1': 0.025, 'B': 0.126}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:49:09,851] Trial 86 finished with value: 0.13014338458801025 and parameters: {'K': 532, 'K1': 0.01, 'B': 0.11}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:49:20,579] Trial 87 finished with value: 0.1307661511543423 and parameters: {'K': 588, 'K1': 0.45, 'B': 0.105}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:49:31,157] Trial 88 finished with value: 0.13115167331445263 and parameters: {'K': 581, 'K1': 0.055, 'B': 0.096}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:49:41,659] Trial 89 finished with value: 0.13092925668361977 and parameters: {'K': 552, 'K1': 0.08, 'B': 0.118}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:49:51,780] Trial 90 finished with value: 0.1310182233359529 and parameters: {'K': 519, 'K1': 0.04, 'B': 0.133}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:50:02,080] Trial 91 finished with value: 0.13122581219139692 and parameters: {'K': 539, 'K1': 0.055, 'B': 0.114}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:50:12,279] Trial 92 finished with value: 0.13103305111134175 and parameters: {'K': 543, 'K1': 0.065, 'B': 0.09999999999999999}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:50:22,628] Trial 93 finished with value: 0.1311665010898415 and parameters: {'K': 564, 'K1': 0.05, 'B': 0.128}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:50:32,665] Trial 94 finished with value: 0.13067718450200916 and parameters: {'K': 535, 'K1': 0.035, 'B': 0.091}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:50:42,416] Trial 95 finished with value: 0.13086994558206433 and parameters: {'K': 503, 'K1': 0.08, 'B': 0.122}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:50:52,708] Trial 96 finished with value: 0.13086994558206433 and parameters: {'K': 574, 'K1': 0.105, 'B': 0.107}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:51:03,442] Trial 97 finished with value: 0.13043994009578744 and parameters: {'K': 604, 'K1': 0.025, 'B': 0.113}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:51:13,713] Trial 98 finished with value: 0.13097374000978634 and parameters: {'K': 558, 'K1': 0.065, 'B': 0.11599999999999999}. Best is trial 31 with value: 0.1312702955175635.

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

[I 2025-01-17 14:51:23,672] Trial 99 finished with value: 0.1311665010898415 and parameters: {'K': 542, 'K1': 0.05, 'B': 0.138}. Best is trial 31 with value: 0.1312702955175635.
Лучшие параметры: {'K': 406, 'K1': 0.05, 'B': 0.14}
CPU times: user 20min 17s, sys: 4min 7s, total: 24min 25s
Wall time: 16min 8s

In [34]:
# формируем и выводим график оптимизации гиперпараметров
optuna.visualization.plot_optimization_history(study, target_name="p_at_k")

In [35]:
# формируем и выводим график важности гиперпараметров
optuna.visualization.plot_param_importances(study, target_name="p_at_k")

In [36]:
# визуализация контуров гиперпараметров
optuna.visualization.plot_contour(study, params=["K1", "B"], target_name="p_at_k")

In [37]:
# визуализация среза
optuna.visualization.plot_slice(study, target_name="p_at_k")

In [38]:
# визуализация прогресса оптимизации для параллельной координатной плоскости
optuna.visualization.plot_parallel_coordinate(study, target_name="p_at_k")

In [39]:
# визуализация соотношения гиперпараметров к целевой метрике
optuna.visualization.plot_edf(study, target_name="p_at_k")

In [40]:
# фиксируем время начала работы
start_time = time.time()
# формируем параметры модели и обучаем её с учетом подобранных параметров
model = BM25Recommender(**best_params, 
                        num_threads=8)


model.fit(train)

# расчитываем метрику precision@k
p_at_k = precision_at_k(model, train, test, K=3)
p_at_k_train = 0
# фиксируем время окончания работы
end_time = time.time()
elapsed_time = end_time - start_time

print(f'Precision@3: {p_at_k:.4f}', f'Параметры модели: {best_params}')
print()
# Вариан 1 - Выбираем случайного пользователя
random_normalized_visitorid = np.random.choice(users)

# Вариант 2 - Вводим оригинальный visitorid
# original_visitorid = 391657
# random_normalized_visitorid = original_visitorid - min_visitorid # приводим его к нормализованному виду

userid = user_to_idx[random_normalized_visitorid]

# получаем рекомендации для пользователя
ids, scores = model.recommend(userid, matrix[userid], N=3, filter_already_liked_items=False)
# преобразуем обратно в оригинальные itemid
original_item_ids = [items[idx] + min_itemid for idx in ids]
# преобразуем обратно в оригинальный visitorid
original_visitorid = random_normalized_visitorid + min_visitorid

# используем pandas для отображения результатов в виде таблицы
rec_user = pd.DataFrame({
    "visitorid": original_visitorid,
    "itemid": original_item_ids,
    "score": scores,
    "already_liked": np.in1d(ids, matrix[userid].indices.ravel())  # преобразуем в одномерный массив
})
print(rec_user)
print()
set1 = set(df[df["visitorid"] == original_visitorid]["itemid"].unique().tolist())
set2 = set(original_item_ids)
print(f'Соответсвие itemid между рекомендациями и фактом {set1&set2}')
print()
print(rec_user["already_liked"].value_counts())

# сохраняем результаты
results_implicit = add_results(results_implicit, "NNM_BM25Recomender_Optuna_best", elapsed_time, p_at_k_train, p_at_k)
display(results_implicit)

  0%|          | 0/95302 [00:00<?, ?it/s]

  0%|          | 0/38759 [00:00<?, ?it/s]

Precision@3: 0.1313 Параметры модели: {'K': 406, 'K1': 0.05, 'B': 0.14}

   visitorid  itemid          score  already_liked
0    1217827   91998  192377.152224           True
1    1217827  379739  172405.985504           True
2    1217827  252314  164277.805157           True

Соответсвие itemid между рекомендациями и фактом {252314, 379739, 91998}

already_liked
True    3
Name: count, dtype: int64

,Model,Time,train_Precision@3,test_Precision@3
0,NNM_CosinRecomender,4.854386,0,0.051156
1,NNM_CosinRecomender_Optuna,5.049159,0,0.052387
2,NNM_ItemItemRecomender,4.798687,0,0.071307
3,NNM_ItemItemRecomender_Optuna,5.474812,0,0.072997
4,NNM_BM25Recomender,4.87209,0,0.125621
5,NNM_BM25Recomender_Optuna,8.314192,0,0.131567
6,MF_ALS,21.649938,0,0.084578
7,MF_ALS_Optuna,52.817272,0,0.10329
8,MF_BPR,25.006213,0,0.024703
9,MF_BPR_Optuna,22.199291,0,0.06069
10,MF_LMF,15.123544,0,0.004167
11,MF_LMF_Optuna,45.255306,0,0.000371
12,NMSLibModel,62.61669,0,0.082902
13,NMSLibModel_Optuna,62.470012,0,0.082976
14,NNM_BM25Recomender_Optuna_best,8.765186,0,0.13127

In [41]:
# cохраняем модель в файл
dump(model, "model/model_Implicit_count_NNM_BM25R_best_light.joblib")

['model/model_Implicit_count_NNM_BM25R_best_light.joblib']

In [42]:
# сохраняем результаты
results_implicit.to_csv("results/results_implicit_count_light.csv", sep=",", index=False)

### 6. Дополнение - пример с сайта библиотеки Impicit

In [ ]:
# загружаем данные
artists, users, artist_user_plays = get_lastfm()  # получение данных о артистах, пользователях и воспроизведениях

# взвешиваем матрицу для уменьшения влияния пользователей, которые слушали одного артиста тысячи раз, а также для снижения веса популярных элементов
artist_user_plays = bm25_weight(artist_user_plays, K1=100, B=0.8)

# получаем транспонированную матрицу, так как большинство функций библиотеки implicit ожидают разреженную матрицу формата (пользователь, элемент), вместо (элемент, пользователь)
user_plays = artist_user_plays.T.tocsr()

# формируем тренировочную и тестовые выборки
train, test = train_test_split(user_plays, train_percentage=0.7, random_state=369)

# формируем параметры модели и обучаем её
model = AlternatingLeastSquares(factors=100, regularization=0.05, alpha=2.0)
model.fit(train)

# расчет метрики precision@k
p_at_k = precision_at_k(model, train, test, K=3)
print(f'Precision@3: {p_at_k:.4f}')

# определяем ID пользователя и получаем три рекомендации
userid = 25365
ids, scores = model.recommend(userid, user_plays[userid], N=7, filter_already_liked_items=False)

# используем pandas для отображения результатов в виде таблицы. Pandas не является зависимостью implicit
rec_user = pd.DataFrame({"artist": artists[ids], "score": scores, "already_liked": np.in1d(ids, user_plays[userid].indices)})
print(rec_user)